/**
 * Vertical placement of a page's components — Composer OWNS height
 * (vertical-ownership plan, Phase 1, 2026-09-02).
 *
 * The paper is fixed and the scale is pinned at the box (decisions.md
 * 2026-09-02, "Section headers are page budget"). The components that fill a
 * page are SYSTEMS, each with measured extents, and SECTION HEADERS, each a
 * fixed reserve above the system that carries the header's measure. This
 * module decides where every system's staff top sits in the page-margin frame
 * and where every header's title band starts. Nothing here reads Verovio's own
 * vertical stacking: every page — a derive's, a lazy mount's, a splice's, the
 * reference gate's — is placed by this one rule over extents Composer measured
 * itself, so a full render and a splice agree by construction and the splice
 * window no longer needs its context lines for geometry.
 *
 * The rule (v1) restates Verovio 6.3's clearance so the visual change against
 * the pre-ownership pages is confined to systems whose extreme content is a
 * <text> element (Verovio's text metrics disagree with the rendered bbox):
 *
 *   page-first:  staffTop = y0 + reserve + max(above, F)
 *   otherwise:   staffTop = prevBottomClearance + reserve + G + max(above, F)
 *   where prevBottomClearance = prev.staffBot + max(prev.below, F)
 *   and   y0 = pageHeaderBottom + HEADER_GAP   (C0 when the page has no header)
 *
 * with F = 6 units (half a staff spacing — Verovio's floor for the first staff
 * of a system and for its bottom alignment), G = 4 units (`spacingSystem`),
 * HEADER_GAP = 2 units (Verovio's `bottomMarginHeader`: the page header —
 * Verovio's `g.pgHead`, the title on page 1 and the autogenerated page number
 * elsewhere — is a page component and the first system's content starts that
 * far below it), and C0 = 5.25 units, the y0 a page without a header element
 * gets (= the autogenerated one-line header's bottom + the gap; calibrated on
 * 30 sonata pages, `cb-placement.js`: residual ≤ 0.1 unit on every
 * glyph-topped page). Consecutive-system gaps under this rule matched
 * Verovio's within 1 unit on 73 of 86 sonata pairs and within 3 on 85.
 * A unit is half a staff space: `10 × the Verovio `unit` option` in SVG user
 * units (80 at unit 8; the crisp zoom presets share it, so every constant is
 * zoom-invariant).
 *
 * Extents are read from the rendered, post-processed system (HEJI text
 * included, section titles excluded — they are page components): `above` is
 * the content top to the first staff's top line, `below` the last staff's
 * bottom line to the content bottom, both in the system's own frame. They need
 * a laid-out SVG (`getBBox`), which the mount pass and the post-surgery snap
 * already flush for; the staff lines are read from the path text.
 *
 * Distribution of slack within the budget (D1 proper) is a later rule; only
 * `placeSystems` changes for it.
 */

/** Vertical space a section header carves out above its system, and the
 *  title baseline's offset into that band (Verovio units × 10, i.e. SVG user
 *  units at unit 8). Recorded on each title as `data-reserve` /
 *  `data-baseline` so a reader can verify a title sits in its band. */
export const SECTION_HEADER_RESERVE = 900;
export const SECTION_HEADER_BASELINE = 360;

/** Placement constants in SVG user units, derived from the Verovio `unit`. */
export interface PageFitConstants {
  /** SVG user units per Verovio unit (half a staff space). */
  unit: number;
  /** Floor for a system's clearance above its first staff and below its last. */
  F: number;
  /** Minimum space between one system's bottom clearance and the next's top. */
  G: number;
  /** First content top for a page WITHOUT a header element. */
  C0: number;
  /** Space between the page header's bottom and the first system's content. */
  headerGap: number;
  /** SVG user units per DEVICE pixel (`1 / ds`), or 0 when unknown. Placement
   *  quantizes every system translate to a whole number of these, which is what
   *  makes a staff's crisp phase independent of where its system is placed —
   *  see `alignStaffRows` and docs/composer-vertical-ownership-plan.md §3.5. */
  grid: number;
  /** Device-pixel phase a staff line must land on to be crisp: ½ for an odd
   *  (1px) stroke, 0 for an even (2px) one. */
  phase: number;
}

/** `scale` and `evenWidth` come from the active CRISP_PRESET; omitted (0 grid)
 *  the placement is unquantized, which is the pre-2026-09-03 behaviour. */
export function pageFitConstants(verovioUnit: number, scale = 0, evenWidth = false): PageFitConstants {
  const unit = 10 * verovioUnit;
  return {
    unit, F: 6 * unit, G: 4 * unit, C0: 5.25 * unit, headerGap: 2 * unit,
    grid: scale > 0 ? 1000 / scale : 0,
    phase: evenWidth ? 0 : 0.5,
  };
}

const fracOf = (x: number): number => ((x % 1) + 1) % 1;

/** Space a system's staff rows a WHOLE number of device pixels apart, leaving
 *  the first row untouched.
 *
 *  Crispness needs every staff line on the device grid. The system's own
 *  translate (chosen in `placeSystems`) puts the FIRST row on the right phase;
 *  everything else only has to keep whole-pixel spacing from it, which is what
 *  this does. Verovio's inter-staff distance is content-dependent and not a
 *  pixel multiple, so without this the lower staff of a grand staff lands at a
 *  different phase and renders blurred.
 *
 *  Why relative and not absolute (2026-09-03, after getting it wrong once):
 *  correcting each row against the SCREEN makes the correction depend on the
 *  render's arbitrary origin — and a system engraved in a splice WINDOW sits at
 *  a different raw `y` than the same system in a full page render (measured:
 *  lineY 6255 vs 6812, different residues). Each render then picks a different
 *  correction, that correction lands in `staffTop`, `measureExtents` folds it
 *  into `above`, and placement — which consumes `above` — puts the system a
 *  whole pixel off. Every element in it is then visibly displaced, while every
 *  staff is still perfectly crisp, so a phase audit sees nothing wrong (page 4
 *  of the sonata: systems 2-4 displaced 10/20/10 units, 2.9 % of pixels).
 *  Relative spacing depends only on the music, so `above` measured from the
 *  uncorrected first row is render-invariant and placement is deterministic. */
export function alignStaffRows(sys: Element, grid: number): number {
  if (!(grid > 0)) return 0;
  const firstMeas = sys.querySelector('g.measure');
  if (!firstMeas) return 0;
  const rowStaves = Array.from(firstMeas.querySelectorAll(':scope > g.staff'));
  if (!rowStaves.length) return 0;
  const refYs = staffLineYs(rowStaves[0]);
  if (!refYs.length) return 0;
  const refY = refYs[0];
  let moved = 0;
  for (const staff of Array.from(sys.querySelectorAll('g.staff'))) {
    const ys = staffLineYs(staff);
    if (!ys.length) continue;
    /* Offset RELATIVE to the system's first staff row, wrapped to the nearest
       whole device pixel. The first row therefore gets exactly 0 and every
       other row gets a distance that is pure intra-system geometry — identical
       in any render of the same music. */
    let rel = (refY - ys[0]) % grid;
    rel = ((rel % grid) + grid) % grid;
    if (rel > grid / 2) rel -= grid;
    const { tx, ty } = translateOf(staff);
    if (Math.abs(rel - ty) < 1e-4) continue;
    staff.setAttribute('transform', `translate(${tx}, ${rel})`);
    moved++;
  }
  return moved;
}

/** A system's vertical extents in its OWN frame (before its transform). */
export interface SysExtents {
  /** y of the first staff's top line (staff transform included). */
  staffTop: number;
  /** y of the last staff's bottom line (staff transform included). */
  staffBot: number;
  /** Content above the first staff's top line (≥ 0). */
  above: number;
  /** Content below the last staff's bottom line (≥ 0). */
  below: number;
}

export interface PlacedSystem {
  /** Target staff top, page-margin frame. */
  top: number;
  /** Translate to apply to the system (`top − staffTop`). */
  ty: number;
  /** Top of the header band above this system, or null when it carries none. */
  bandTop: number | null;
  /** Actual content bottom at this placement (staffBot + below, translated). */
  contentBottom: number;
}

/** `M x1 y1 L x2 y2` of a horizontal path, or null. */
export function parseLinePath(d: string | null): { x1: number; y1: number; x2: number; y2: number } | null {
  const m = /M\s*(-?[\d.]+)[\s,]+(-?[\d.]+)\s*L\s*(-?[\d.]+)[\s,]+(-?[\d.]+)/.exec(d ?? '');
  if (!m) return null;
  const y1 = Number(m[2]), y2 = Number(m[4]);
  if (Math.abs(y1 - y2) > 1e-6) return null;
  return { x1: Number(m[1]), y1, x2: Number(m[3]), y2 };
}

/** The translate of an element's `transform` attribute (text read). */
export function translateOf(el: Element): { tx: number; ty: number } {
  const m = /translate\(\s*(-?[\d.]+)(?:[\s,]+(-?[\d.]+))?/.exec(el.getAttribute('transform') ?? '');
  return m ? { tx: Number(m[1]), ty: Number(m[2] ?? 0) } : { tx: 0, ty: 0 };
}

/** Horizontal staff-line ys of a `g.staff`, ascending, in the staff's frame. */
function staffLineYs(staff: Element): number[] {
  const ys: number[] = [];
  for (const p of Array.from(staff.children)) {
    if (p.localName !== 'path') continue;
    const d = parseLinePath(p.getAttribute('d'));
    if (d) ys.push(d.y1);
  }
  return ys.sort((a, b) => a - b);
}

/** Read a rendered system's extents. Needs layout for the bbox (the element
 *  must be attached); the staff frame is text. Null when the system has no
 *  readable staff lines or an empty bbox. */
export function measureExtents(sys: SVGGraphicsElement): SysExtents | null {
  const first = sys.querySelector('g.measure');
  if (!first) return null;
  const staves = Array.from(first.querySelectorAll(':scope > g.staff'));
  if (!staves.length) return null;
  const topStaff = staves[0], botStaff = staves[staves.length - 1];
  const topYs = staffLineYs(topStaff), botYs = staffLineYs(botStaff);
  if (!topYs.length || !botYs.length) return null;
  const staffTop = topYs[0] + translateOf(topStaff).ty;
  const staffBot = botYs[botYs.length - 1] + translateOf(botStaff).ty;
  let bb: DOMRect;
  try { bb = sys.getBBox(); } catch { return null; }
  if (!(bb.height > 0)) return null;
  return {
    staffTop, staffBot,
    above: Math.max(0, staffTop - bb.y),
    below: Math.max(0, (bb.y + bb.height) - staffBot),
  };
}

/** Place systems top to bottom in the page-margin frame. `y0` is where the
 *  first system's content may start (below the page header); `reserve` is the
 *  section-header budget above each system (0 for most). Pure arithmetic. */
export function placeSystems(items: Array<{ ext: SysExtents; reserve: number }>, k: PageFitConstants, y0: number, originPhase = 0): PlacedSystem[] {
  const out: PlacedSystem[] = [];
  /* DEAD END, measured 2026-09-03: quantizing every term (lead, reserve, the
     above/below clearances and the accumulator) to the grid made exactness
     WORSE — 280 of 338 (edit, page) pairs exact fell to 199, and six pairs
     came back over the old 30-unit tolerance. It reads like it should remove
     rounding noise, but `top` carries `staffTop`'s non-grid crisp-phase
     residue, so rounding the ACCUMULATOR adds a second noisy decision on top
     of the one in `ty` instead of eliminating it. One rounding per system, on
     an unrounded accumulator, is strictly better. */
  let y = 0;   // running bottom clearance of what is above
  for (let i = 0; i < items.length; i++) {
    const { ext, reserve } = items[i];
    const lead = i === 0 ? y0 : k.G;
    const rawTop = y + reserve + lead + Math.max(ext.above, k.F);
    /* Quantize the TRANSLATE, not the top: `alignStaffRows` put every staff on
       its crisp phase assuming the system moves by a whole number of device
       pixels, so `ty` is what must land on the grid. `top` is then whatever
       that translate actually produces — the model states where the system IS,
       never where it was asked to be. */
    const ty0 = rawTop - ext.staffTop;
    /* Nudge the system so its FIRST staff row lands on the crisp phase (that
       row carries no correction of its own — see alignStaffRows), and the rows
       below it, spaced a whole number of pixels away, land on it too. This
       replaces quantizing `ty` to the grid: the phase, not the translate, is
       what has to be right, and putting it here keeps every staff correction
       render-invariant. */
    let ty = ty0;
    if (k.grid > 0) {
      const ds = 1 / k.grid;
      const cur = ((((originPhase + (ty0 + ext.staffTop) * ds) % 1) + 1) % 1);
      let d = (((k.phase - cur) % 1) + 1) % 1;
      if (d > 0.5) d -= 1;
      ty = ty0 + d / ds;
    }
    const top = ext.staffTop + ty;
    const contentTop = top - ext.above;
    const span = ext.staffBot - ext.staffTop;
    out.push({
      top,
      ty,
      bandTop: reserve > 0 ? contentTop - reserve : null,
      contentBottom: top + span + ext.below,
    });
    y = top + span + Math.max(ext.below, k.F);
  }
  return out;
}

/** Index of the first system whose content bottom passes `limit` (the paper
 *  bottom in the page-margin frame), or −1 when every system fits. */
export function foldIndex(placed: PlacedSystem[], limit: number, tolerance = 0): number {
  for (let i = 0; i < placed.length; i++) {
    if (placed[i].contentBottom > limit + tolerance) return i;
  }
  return -1;
}

/** Per-line extents store (keyed by a line's start-measure id). Filled as a
 *  by-product of every placement pass; Phase 2 reads it for pages that are not
 *  mounted. Cleared by the owner on any key change (unit / scale / heji /
 *  document replace). */
export class ExtentsStore {
  private map = new Map<string, SysExtents>();
  get(startId: string): SysExtents | undefined { return this.map.get(startId); }
  set(startId: string, ext: SysExtents): void { this.map.set(startId, ext); }
  delete(startId: string): void { this.map.delete(startId); }
  clear(): void { this.map.clear(); }
  get size(): number { return this.map.size; }
}
