// Canvas size + viewport range.
//
// Bounds are per-outline: each outline mode picks its own cell set so the
// canvas fits exactly what's visible. Within (rotation, outline, tuning)
// the canvas size is static — refNote changes don't trigger resizes.
//
// Piano-outline bounds depend on the picker output (TH ranking across
// 88 MIDI notes for every reachable refNote/septimalShift) which is
// expensive to evaluate. We do that offline once via
// `tools/bounds-probe/compute-bounds.mjs` and hardcode the resulting
// kbMinW × CH values in the table below. Re-run the probe and update
// PIANO_BOUNDS_TABLE if any of:
//   • src/tuning/ratios.ts (jiRatio, TH reduction) changes,
//   • src/tuning/regions.ts (region adjustments) changes,
//   • src/render/draw.ts compute88PianoCoords (picker / tiebreak) changes,
//   • src/layout/geometry.ts (hexR, dxH, dyH, tilt angles) changes,
//   • the SEPTIMAL_SHIFT or refR wrap ranges change.
//
// kbOffY is forced to 0 — content is symmetric about the canvas vertical
// midline; CH grows to fit the larger of |minY| / |maxY|.

import { baseKeys } from '../layout/baseKeys.js';
import { qwertyKeys } from '../input/qwerty.js';
import { hexR, dxH, dyH, cosT, sinT, hexToScreen, currentRotationMode } from '../layout/geometry.js';
import type { OutlineMode, RotationMode } from '../state/persistence.js';
import { tuning } from '../state/tuning.js';
import { view } from '../state/view.js';

/** Solve for the lattice viewport center (viewQ, viewR) such that
 *  hexToScreen places refNote at screen-X = 0 (horizontal center) and
 *  MIDI 64's cell at screen-Y = 0 (vertical center) under the active tilt.
 *
 *  hexToScreen (geometry.ts) factors out to (with y = r·dyH):
 *    sx(q, r) = q·dxH·cosT + r·(dxH·0.5·cosT − dyH·sinT) = A·q + B·r
 *    sy(q, r) = −q·dxH·sinT − r·(dxH·0.5·sinT + dyH·cosT) = C·q + D·r
 *  We want screen positions of (refQ − viewQ, refR − viewR) → sx = 0
 *  and (m64Q − viewQ, m64R − viewR) → sy = 0, giving the linear system
 *    A·viewQ + B·viewR = A·refQ + B·refR
 *    C·viewQ + D·viewR = C·m64Q + D·m64R
 *  whose determinant A·D − B·C = −dxH·dyH is tilt-independent. */
export function computePianoViewCenter(
  refQ: number, refR: number, m64Q: number, m64R: number,
): [number, number] {
  const A = dxH * cosT;
  const B = dxH * 0.5 * cosT - dyH * sinT;
  const C = -dxH * sinT;
  const D = -dxH * 0.5 * sinT - dyH * cosT;
  const rhsX = A * refQ + B * refR;
  const rhsY = C * m64Q + D * m64R;
  const det = A * D - B * C;
  return [
    (D * rhsX - B * rhsY) / det,
    (-C * rhsX + A * rhsY) / det,
  ];
}

interface CanvasMetrics { kbMinW: number; CH: number; }

/* ── precomputed piano-outline bounds matrix ────────────────────────────────
   Generated by `node tools/bounds-probe/compute-bounds.mjs`. Tuning bucket
   '5' covers 5-limit AND 12-TET (jiRatio is identical when septimalEnabled
   is false). '7' covers 7-limit and unions across the full septimalShift
   wrap range. Lumatone and QWERTY outlines are tuning-independent. "none"
   = union of lumatone + qwerty + piano per tuning. */
const PIANO_BOUNDS_TABLE: Record<RotationMode, Record<'5' | '7', CanvasMetrics>> = {
  verticalFreq: { '5': { kbMinW: 1115, CH: 418 }, '7': { kbMinW: 1808, CH: 418 } },
  lumatone:     { '5': { kbMinW: 1240, CH: 345 }, '7': { kbMinW: 1883, CH: 590 } },
  piano:        { '5': { kbMinW: 1257, CH: 307 }, '7': { kbMinW: 1798, CH: 751 } },
};

/* Lumatone / QWERTY are static cell sets (no tuning dependence). Project
   live each time — it's fast and avoids the hardcoding-staleness risk for
   sets that aren't expensive. */
function staticOutlineCells(outline: 'lumatone' | 'qwerty'): ReadonlyArray<readonly [number, number]> {
  if (outline === 'lumatone') return baseKeys;
  return qwertyKeys;
}

interface ScreenBounds { minX: number; maxX: number; minY: number; maxY: number; }

function projectStatic(cells: ReadonlyArray<readonly [number, number]>, b: ScreenBounds): void {
  for (const [q, r] of cells) {
    const p = hexToScreen(q, r);
    if (p.sx < b.minX) b.minX = p.sx;
    if (p.sx > b.maxX) b.maxX = p.sx;
    if (p.sy < b.minY) b.minY = p.sy;
    if (p.sy > b.maxY) b.maxY = p.sy;
  }
}

/* Resolve the live outline mode from the DOM. Falls back to 'lumatone' when
   the select element is absent (e.g. very early init before HTML parsed). */
function currentOutlineMode(): OutlineMode {
  const sel = document.getElementById('selOutline') as HTMLSelectElement | null;
  const v = sel?.value;
  if (v === 'qwerty' || v === 'piano' || v === 'none') return v;
  return 'lumatone';
}

/* Re-project the active outline through current tilt and refresh
   view.kbMinW / view.CH. Called at module load and on rotation/outline/
   tuning change. Piano-outline bounds are read from the hardcoded
   PIANO_BOUNDS_TABLE; lumatone/qwerty are projected live (fast). */
export function recomputeCanvasBounds(outlineOverride?: OutlineMode): void {
  const outline = outlineOverride ?? currentOutlineMode();
  const padY = hexR + dxH * 0.5;
  const padX = dxH * 1.5 + hexR;
  let kbMinW = 0, CH = 0;

  if (outline === 'lumatone' || outline === 'qwerty' || outline === 'none') {
    const b: ScreenBounds = { minX: 1e9, maxX: -1e9, minY: 1e9, maxY: -1e9 };
    if (outline === 'lumatone' || outline === 'none') projectStatic(staticOutlineCells('lumatone'), b);
    if (outline === 'qwerty' || outline === 'none') projectStatic(staticOutlineCells('qwerty'), b);
    kbMinW = Math.ceil((Math.max(-b.minX, b.maxX) + padX) * 2);
    CH = Math.ceil(2 * Math.max(Math.abs(b.minY), Math.abs(b.maxY)) + 2 * padY);
  }
  if (outline === 'piano' || outline === 'none') {
    /* Piano table is keyed by tuning bucket — '5' covers 5-limit + 12-TET
       (which share the picker output), '7' covers 7-limit. */
    const bucket: '5' | '7' = tuning.septimalEnabled ? '7' : '5';
    const m = PIANO_BOUNDS_TABLE[currentRotationMode][bucket];
    /* For "none", take the max of piano vs lumatone+qwerty already computed. */
    kbMinW = Math.max(kbMinW, m.kbMinW);
    CH = Math.max(CH, m.CH);
  }
  view.kbMinW = kbMinW;
  view.CH = CH;
  view.kbOffY = 0;
}
recomputeCanvasBounds();

export function sizeCanvas(): void {
  const wrapPad = 24; /* 12px padding each side of .wrap */
  view.CW = Math.max(400, window.innerWidth - wrapPad);
}

export interface VisibleRange {
  qMin: number;
  qMax: number;
  rMin: number;
  rMax: number;
}

/* visible range computed per-frame based on current view */
export function getVisibleRange(vq: number, vr: number): VisibleRange {
  const corners: [number, number][] = [
    [-view.CW / 2, -(view.CH / 2 + view.kbOffY)],
    [view.CW / 2, -(view.CH / 2 + view.kbOffY)],
    [view.CW / 2, view.CH / 2 - view.kbOffY],
    [-view.CW / 2, view.CH / 2 - view.kbOffY],
  ];
  let qLo = 1e9, qHi = -1e9, rLo = 1e9, rHi = -1e9;
  corners.forEach(function (c) {
    const ux = c[0] * cosT - c[1] * sinT;
    const uy = c[0] * sinT + c[1] * cosT;
    const rRel = -uy / dyH;
    const qRel = (ux - rRel * dxH * 0.5) / dxH;
    const qAbs = qRel + vq, rAbs = rRel + vr;
    if (qAbs < qLo) qLo = qAbs;
    if (qAbs > qHi) qHi = qAbs;
    if (rAbs < rLo) rLo = rAbs;
    if (rAbs > rHi) rHi = rAbs;
  });
  return {
    qMin: Math.floor(qLo) - 2, qMax: Math.ceil(qHi) + 2,
    rMin: Math.floor(rLo) - 2, rMax: Math.ceil(rHi) + 2,
  };
}
