// Selection clipboard. Serializes a SelectionState to a portable MEI fragment
// (an <hkl:clipboard> wrapper carrying the selected content plus enough
// metadata to re-anchor on paste), writes to navigator.clipboard, reads back,
// and parses into a ClipboardContents discriminated union.
//
// Copy/cut/paste action wiring lives in input.ts; this module is the data
// layer — no DOM-mutation of the model happens here (paste is sequenced
// from input.ts so it can drive setStatus + reRender).

import { type ComposerModel, type Voice, MEI_NS } from './model.js';
import type { SelectionState, Staff } from './selection.js';
import { readTimeSig } from './beams.js';
import { realTicks } from './ticks.js';

const HKL_NS = 'https://hexkeylab.com/ns/mei';
const CLIPBOARD_LOCAL = 'clipboard';

export type ClipboardContents =
  | {
      kind: 'beat';
      sourceVoice: Voice;
      elements: Element[];      // cloned, ids stripped, ties trimmed at boundary
      durationTicks: number;
      sourceTimeSig: string;    // "count/unit"
    }
  | {
      kind: 'measure';
      sourceStaffRange: { first: Staff; last: Staff };
      measures: Element[];      // cloned <measure> elements (full structure)
      expressions: Element[];   // <dynam>/<hairpin> whose tstamp falls in range
      sourceTimeSig: string;
    };

function timeSigString(model: ComposerModel): string {
  const ts = readTimeSig(model.getDoc());
  return ts.count + '/' + ts.unit;
}

/** Recursively strip @xml:id from `el` and all descendants. New ids are
 *  regenerated by the paste path (so cloned content doesn't collide with
 *  existing live-doc ids). */
function stripIds(el: Element): void {
  el.removeAttributeNS('http://www.w3.org/XML/1998/namespace', 'id');
  // Some MEI elements use the unprefixed form too; remove defensively.
  el.removeAttribute('xml:id');
  for (const c of Array.from(el.children)) stripIds(c);
}

/** Strip tie state on the boundary-most notes of a cloned content element.
 *  Position `'first'` = the element is the first content of the selection
 *  (any incoming tie is from outside → drop). `'last'` = the element is the
 *  last (any outgoing tie targets outside → drop). Interior ties survive
 *  untouched; normalizeTies in the destination will derive partners after
 *  paste. */
function trimBoundaryTies(el: Element, position: 'first' | 'last' | 'both'): void {
  const notes = Array.from(el.querySelectorAll('note'));
  // If `el` is itself a <note>, include it (querySelectorAll excludes self).
  if (el.localName === 'note') notes.push(el);
  for (const n of notes) {
    const tie = n.getAttribute('tie');
    if (position === 'first' || position === 'both') {
      // Drop incoming-side.
      if (tie === 't') n.removeAttribute('tie');
      else if (tie === 'm') n.setAttribute('tie', 'i');
    }
    if (position === 'last' || position === 'both') {
      // Drop outgoing-side.
      if (tie === 'i') n.removeAttribute('tie');
      else if (tie === 'm') n.setAttribute('tie', 't');
      n.removeAttribute('data-pending-tie');
    }
    // tie-partner is a derived attribute, never preserved across copy.
    n.removeAttribute('data-tie-partner');
  }
}

/** Walk a voice's layer-level content children and collect those whose
 *  [absStart, absEnd) falls within [tLo, tHi). Returns clones with ids
 *  stripped. */
function collectBeatContent(
  model: ComposerModel,
  voice: Voice,
  tLo: number,
  tHi: number,
): Element[] {
  const measures = model.allMeasures();
  const measureT = model.measureTicks();
  const out: Element[] = [];
  for (let mi = 0; mi < measures.length; mi++) {
    const measureStart = mi * measureT;
    if (measureStart >= tHi) break;
    if (measureStart + measureT <= tLo) continue;
    const m = measures[mi];
    const staffN = voice <= 2 ? 1 : 2;
    const layerN = voice === 1 || voice === 3 ? 1 : 2;
    const staff = Array.from(m.querySelectorAll('staff')).find(
      (s) => s.getAttribute('n') === String(staffN),
    );
    if (!staff) continue;
    const layer = Array.from(staff.querySelectorAll('layer')).find(
      (l) => l.getAttribute('n') === String(layerN),
    );
    if (!layer) continue;
    let cursor = measureStart;
    for (const child of Array.from(layer.children)) {
      const ln = child.localName;
      if (ln !== 'chord' && ln !== 'note' && ln !== 'rest' && ln !== 'tuplet') continue;
      const dur = realTicks(child);
      const cEnd = cursor + dur;
      if (cursor >= tLo - 1e-6 && cEnd <= tHi + 1e-6) {
        out.push(child.cloneNode(true) as Element);
      }
      cursor = cEnd;
    }
  }
  for (const el of out) stripIds(el);
  return out;
}

/** Clone the selected staves (firstStaff..lastStaff) within each measure
 *  [mLo..mHi]. Returns one <measure> clone per source measure, restricted
 *  to the selected staves' layers (other staves stripped). xml:ids stripped. */
function collectMeasureContent(
  model: ComposerModel,
  mLo: number,
  mHi: number,
  firstStaff: Staff,
  lastStaff: Staff,
): Element[] {
  const measures = model.allMeasures();
  const out: Element[] = [];
  for (let mi = mLo; mi <= mHi && mi < measures.length; mi++) {
    const m = measures[mi];
    const clone = m.cloneNode(true) as Element;
    // Remove staves outside the range. Iterate the clone's <staff> children.
    for (const s of Array.from(clone.querySelectorAll('staff'))) {
      const sn = parseInt(s.getAttribute('n') ?? '0', 10);
      if (sn < firstStaff || sn > lastStaff) {
        s.parentNode?.removeChild(s);
      }
    }
    // Strip <tempo>/<dynam>/<hairpin> control children of <measure> — those
    // are tstamp-anchored and we collect them separately into `expressions`.
    for (const ctrl of Array.from(clone.children)) {
      const ln = ctrl.localName;
      if (ln === 'dynam' || ln === 'hairpin' || ln === 'tempo' || ln === 'fermata') {
        clone.removeChild(ctrl);
      }
    }
    stripIds(clone);
    out.push(clone);
  }
  return out;
}

/** Collect <dynam>/<hairpin> elements anchored within the source measure
 *  range AND staves. Returns deep clones with ids stripped. */
function collectMeasureExpressions(
  model: ComposerModel,
  mLo: number,
  mHi: number,
  firstStaff: Staff,
  lastStaff: Staff,
): Element[] {
  const measures = model.allMeasures();
  const out: Element[] = [];
  for (let mi = mLo; mi <= mHi && mi < measures.length; mi++) {
    const m = measures[mi];
    for (const ctrl of Array.from(m.children)) {
      const ln = ctrl.localName;
      if (ln !== 'dynam' && ln !== 'hairpin') continue;
      const staff = parseInt(ctrl.getAttribute('staff') ?? '0', 10);
      if (staff < firstStaff || staff > lastStaff) continue;
      const clone = ctrl.cloneNode(true) as Element;
      // Tag with source measure offset so paste can re-anchor.
      clone.setAttribute('data-hkl-src-measure-offset', String(mi - mLo));
      stripIds(clone);
      out.push(clone);
    }
  }
  return out;
}

/** Build the <hkl:clipboard> wrapper XML string for the given selection. */
export function serializeClipboard(model: ComposerModel, sel: SelectionState): string {
  /* createDocument already declares xmlns:hkl on the root via the qualified
   * name 'hkl:clipboard'. Re-declaring xmlns:hkl via setAttribute produced a
   * duplicate-attribute error when Firefox parsed the round-tripped string
   * (Chromium silently tolerated it). Set the default xmlns to the MEI
   * namespace via setAttributeNS so MEI children (note/chord/rest/measure)
   * resolve correctly; let createDocument own the hkl: declaration. */
  const doc = document.implementation.createDocument(HKL_NS, 'hkl:clipboard', null);
  const root = doc.documentElement;
  root.setAttributeNS('http://www.w3.org/2000/xmlns/', 'xmlns', MEI_NS);
  root.setAttribute('timeSig', timeSigString(model));

  if (sel.kind === 'beat') {
    const lo = Math.min(sel.anchor, sel.movable);
    const hi = Math.max(sel.anchor, sel.movable);
    const tLo = model.getTickPositionAt(sel.voice, lo);
    const tHi = model.getTickPositionAt(sel.voice, hi);
    const elements = collectBeatContent(model, sel.voice, tLo, tHi);
    // Trim ties at boundaries.
    if (elements.length === 1) {
      trimBoundaryTies(elements[0], 'both');
    } else if (elements.length > 1) {
      trimBoundaryTies(elements[0], 'first');
      trimBoundaryTies(elements[elements.length - 1], 'last');
    }
    root.setAttribute('kind', 'beat');
    root.setAttribute('voice', String(sel.voice));
    root.setAttribute('durationTicks', String(tHi - tLo));
    const content = doc.createElementNS(HKL_NS, 'hkl:content');
    for (const e of elements) {
      content.appendChild(doc.importNode(e, true));
    }
    root.appendChild(content);
  } else {
    const mLo = Math.min(sel.anchorMeasure, sel.movableMeasure);
    const mHi = Math.max(sel.anchorMeasure, sel.movableMeasure);
    const measures = collectMeasureContent(model, mLo, mHi, sel.firstStaff, sel.lastStaff);
    const expressions = collectMeasureExpressions(model, mLo, mHi, sel.firstStaff, sel.lastStaff);
    root.setAttribute('kind', 'measure');
    root.setAttribute('staffFirst', String(sel.firstStaff));
    root.setAttribute('staffLast', String(sel.lastStaff));
    root.setAttribute('measureCount', String(mHi - mLo + 1));
    const mWrap = doc.createElementNS(HKL_NS, 'hkl:measures');
    for (const m of measures) mWrap.appendChild(doc.importNode(m, true));
    root.appendChild(mWrap);
    if (expressions.length > 0) {
      const eWrap = doc.createElementNS(HKL_NS, 'hkl:expressions');
      for (const e of expressions) eWrap.appendChild(doc.importNode(e, true));
      root.appendChild(eWrap);
    }
  }
  return new XMLSerializer().serializeToString(doc);
}

/** Parse an <hkl:clipboard> fragment back into ClipboardContents. Returns
 *  null on parse failure or non-HKL root. */
export function parseClipboard(text: string): ClipboardContents | null {
  if (!text || !text.trim()) return null;
  let doc: Document;
  try {
    doc = new DOMParser().parseFromString(text, 'application/xml');
  } catch {
    return null;
  }
  if (doc.querySelector('parsererror')) return null;
  const root = doc.documentElement;
  if (!root || root.namespaceURI !== HKL_NS || root.localName !== CLIPBOARD_LOCAL) return null;
  const kind = root.getAttribute('kind');
  const sourceTimeSig = root.getAttribute('timeSig') ?? '4/4';
  if (kind === 'beat') {
    const voiceRaw = parseInt(root.getAttribute('voice') ?? '1', 10);
    if (!(voiceRaw >= 1 && voiceRaw <= 4)) return null;
    const durationTicks = parseFloat(root.getAttribute('durationTicks') ?? '0');
    const content = root.getElementsByTagNameNS(HKL_NS, 'content')[0];
    if (!content) return null;
    const elements: Element[] = [];
    for (const c of Array.from(content.children)) {
      elements.push(c.cloneNode(true) as Element);
    }
    return {
      kind: 'beat',
      sourceVoice: voiceRaw as Voice,
      elements,
      durationTicks,
      sourceTimeSig,
    };
  }
  if (kind === 'measure') {
    const sf = parseInt(root.getAttribute('staffFirst') ?? '1', 10);
    const sl = parseInt(root.getAttribute('staffLast') ?? '1', 10);
    if (!((sf === 1 || sf === 2) && (sl === 1 || sl === 2))) return null;
    const mWrap = root.getElementsByTagNameNS(HKL_NS, 'measures')[0];
    if (!mWrap) return null;
    const measures: Element[] = [];
    for (const c of Array.from(mWrap.children)) {
      if (c.localName === 'measure') measures.push(c.cloneNode(true) as Element);
    }
    const expressions: Element[] = [];
    const eWrap = root.getElementsByTagNameNS(HKL_NS, 'expressions')[0];
    if (eWrap) {
      for (const c of Array.from(eWrap.children)) {
        expressions.push(c.cloneNode(true) as Element);
      }
    }
    return {
      kind: 'measure',
      sourceStaffRange: { first: sf as Staff, last: sl as Staff },
      measures,
      expressions,
      sourceTimeSig,
    };
  }
  return null;
}

/* OS clipboard I/O is done via the DOM `copy` / `cut` / `paste` events in
 * input.ts — they fire synchronously on user gesture, expose
 * `event.clipboardData` directly, and (critically) do NOT trigger Firefox's
 * `clipboard-read` permission prompt. `navigator.clipboard.readText()` was
 * the previous approach but it surfaces a "Paste" UI in Firefox and often
 * resolves with empty/stale data even after the user accepts. */
