// Sample engine: instrument library + voice lifecycle.
// IIFE is preserved verbatim from v0.9 — do not refactor internals without
// reading docs/lessons.md (sample-loop invariants: never source.loop=true,
// all wraps via scheduleSegmentSwitch, commitRampSync integrates in-flight
// ramp position).

import { recordSeamEvent } from './diagnostics/loopOverlay.js';

export const SampleEngine = (function () {
  var RELEASE_SCALE = 0.5; /* global multiplier on per-instrument release times */
  var INSTRUMENTS: Record<string, any> = {
    piano:{
      name:'Grand Piano (Salamander)',
      baseUrl:'https://tonejs.github.io/audio/salamander/',
      ext:'.mp3',
      releaseTime:0.15,volume:1.0,
      loop:false,decays:true,
      samples:[
        {name:'A0',freq:27.5},{name:'C1',freq:32.703},{name:'Ds1',freq:38.891},{name:'Fs1',freq:46.249},
        {name:'A1',freq:55},{name:'C2',freq:65.406},{name:'Ds2',freq:77.782},{name:'Fs2',freq:92.499},
        {name:'A2',freq:110},{name:'C3',freq:130.81},{name:'Ds3',freq:155.56},{name:'Fs3',freq:185},
        {name:'A3',freq:220},{name:'C4',freq:261.63},{name:'Ds4',freq:311.13},{name:'Fs4',freq:369.99},
        {name:'A4',freq:440},{name:'C5',freq:523.25},{name:'Ds5',freq:622.25},{name:'Fs5',freq:739.99},
        {name:'A5',freq:880},{name:'C6',freq:1046.5},{name:'Ds6',freq:1244.5},{name:'Fs6',freq:1480},
        {name:'A6',freq:1760},{name:'C7',freq:2093},{name:'Ds7',freq:2489}
      ]
    },
    violin:{
      name:'Violin',baseUrl:'https://gleitz.github.io/midi-js-soundfonts/FluidR3_GM/violin-mp3/',
      ext:'.mp3',releaseTime:0.3,volume:1.0,loop:true,decays:false,vibrato:true,
      /* Generated by the vibrato-aware analyzer (prepareLoopVibrato, AMP mode
         with correlation-based waveform-phase snapping). */
      samples:[
        {name:'G3',freq:196,loopPts:[0.71834,0.88147,1.06519,1.26399,1.44247,1.63129,1.82524,2.02429,2.40705,2.601,2.80005,2.98887],trimStart:0.0039,slopeCV:0.123},
        {name:'B3',freq:246.94,loopPts:[0.83905,1.01388,1.18868,1.36351,1.53832,1.71315,1.88796,2.06279,2.2376,2.4124,2.58317,2.76202,2.93685],trimStart:0.0025,slopeCV:0.086},
        {name:'D4',freq:293.66,loopPts:[0.96454,1.15898,1.3534,1.54785,1.74227,1.94011,2.13116,2.329,2.52005,2.71787,2.90891],trimStart:0.0032,slopeCV:0.076},
        {name:'F4',freq:349.23,loopPts:[0.89447,1.05753,1.22045,1.4122,1.59819,1.78993,1.97592,2.16766,2.35653,2.5454,2.73426,2.91737],trimStart:0.0027,slopeCV:0.162},
        {name:'Ab4',freq:415.3,loopPts:[1.21306,1.38896,1.56483,1.7407,1.91658,2.09488,2.26834,2.44424,2.62011,2.79599,2.97188],trimStart:0.0159,slopeCV:0.109},
        {name:'B4',freq:493.88,loopPts:[1.01626,1.16415,1.31206,1.45995,1.60785,1.75574,1.90365,2.05154,2.19943,2.34937,2.49524,2.64313,2.79306,2.93893],trimStart:0.0137,slopeCV:0.092},
        {name:'E5',freq:659.26,loopPts:[1.02853,1.2258,1.42605,1.61717,1.82197,2.01764,2.21789,2.41204,2.61381,2.81408],trimStart:0.003,slopeCV:0.089},
        {name:'Gb5',freq:739.99,loopPts:[0.81193,1.22397,1.42268,1.61735,1.81336,2.00937,2.20537,2.40138,2.59603,2.79206,2.98671],trimStart:0.0106,slopeCV:0.124},
        {name:'Ab5',freq:830.61,loopPts:[0.72435,1.0866,1.26243,1.6129,1.96215,2.13798,2.31383,2.48846,2.66429,2.83528],trimStart:0.0095,slopeCV:0.117},
        {name:'Db6',freq:1108.73,loopPts:[0.94946,1.33077,1.52043,1.71111,1.89723,2.08152,2.27678,2.4629,2.6481,2.8388],trimStart:0.003,slopeCV:0.122},
        {name:'E6',freq:1318.51,loopPts:[1.26587,1.45132,1.63673,1.82218,2.00762,2.19306,2.3785,2.56392,2.74937,2.93481],trimStart:0.0036,slopeCV:0.089},
        {name:'Gb6',freq:1479.98,loopPts:[1.13522,1.331,1.5315,1.732,1.92778,2.12762,2.32812,2.5239,2.7244,2.92018],trimStart:0.0037,slopeCV:0.186},
        {name:'Ab6',freq:1661.22,loopPts:[1.01032,1.36637,1.54138,1.72122,1.89685,2.07247,2.2481,2.42853,2.60415,2.77857,2.959],trimStart:0.0034,slopeCV:0.177},
        {name:'B6',freq:1975.53,loopPts:[0.99902,1.17483,1.35011,1.52082,1.6961,1.87138,2.04156,2.21737,2.39215,2.56744,2.73812,2.91392],trimStart:0.0026,slopeCV:0.203},
        {name:'C7',freq:2093,loopPts:[0.94351,1.10946,1.26959,1.43986,1.6005,1.76546,1.93141,2.09637,2.26181,2.42245,2.58741,2.75336,2.91302],trimStart:0.0025,slopeCV:0.197}
      ]
    },
    viola:{
      name:'Viola',baseUrl:'https://gleitz.github.io/midi-js-soundfonts/FluidR3_GM/viola-mp3/',
      ext:'.mp3',releaseTime:0.3,volume:1.0,loop:true,decays:false,vibrato:true,
      /* Generated by the vibrato-aware analyzer (prepareLoopVibrato, AMP mode
         with correlation-based waveform-phase snapping). */
      samples:[
        {name:'Db3',freq:138.59,loopPts:[0.45066,0.61635,0.82517,1.01964,1.2141,1.40857,1.60306,1.79753,1.99202,2.18649,2.38095,2.57544,2.76991,2.96438],trimStart:0.0042,slopeCV:0.088},
        {name:'Eb3',freq:155.56,loopPts:[0.64571,0.85857,1.06492,1.27762,1.49032,1.70304,1.91574,2.12844,2.34116,2.55385,2.76658,2.97927],trimStart:0.0041,slopeCV:0.123},
        {name:'F3',freq:174.61,loopPts:[0.57943,0.76327,0.95281,1.52129,1.71079,1.90032,2.0898,2.27927,2.46884,2.84782],trimStart:0.0038,slopeCV:0.121},
        {name:'Ab3',freq:207.65,loopPts:[1.29986,1.4737,1.66694,1.86016,2.05338,2.24662,2.43984,2.63306,2.8263],trimStart:0.004,slopeCV:0.29},
        {name:'C4',freq:261.63,loopPts:[0.74293,0.98408,1.21005,1.44361,1.67719,1.91077,2.14052,2.37791,2.61533,2.84889],trimStart:0.0157,slopeCV:0.095},
        {name:'D4',freq:293.66,loopPts:[0.65769,0.88277,1.08406,1.29215,1.50025,1.71175,1.91642,2.12111,2.32921,2.5373,2.7522,2.95689],trimStart:0.0141,slopeCV:0.08},
        {name:'Gb4',freq:369.99,loopPts:[0.51184,0.91721,1.11732,1.31746,1.51488,1.71771,1.91785,2.11796,2.3181,2.51821,2.71834,2.91848],trimStart:0.0066,slopeCV:0.171},
        {name:'Ab4',freq:415.3,loopPts:[0.8173,0.99317,1.17147,1.35218,1.52805,1.70875,1.88465,2.06535,2.24122,2.41952,2.60023,2.7761,2.9568],trimStart:0.006,slopeCV:0.163},
        {name:'C5',freq:523.25,loopPts:[1.28819,1.52401,1.75791,1.99562,2.22762,2.46916,2.94077],trimStart:0.0051,slopeCV:0.098},
        {name:'Eb5',freq:622.25,loopPts:[1.18941,1.42088,1.65234,1.88383,2.11367,2.34515,2.5734,2.80971],trimStart:0.0039,slopeCV:0.136},
        {name:'F5',freq:698.46,loopPts:[1.0598,1.26458,1.47079,1.68132,1.8861,2.09231,2.2971,2.50331,2.70952,2.91862],trimStart:0.0037,slopeCV:0.126},
        {name:'Ab5',freq:830.61,loopPts:[0.90587,1.08578,1.25732,1.43605,1.6076,1.78272,1.95787,2.1378,2.30814,2.48329,2.65961,2.83596],trimStart:0.0094,slopeCV:0.077},
        {name:'B5',freq:987.77,loopPts:[1.4754,1.64433,1.81429,1.98016,2.15111,2.31701,2.48696,2.65794,2.82687,2.99782],trimStart:0.0118,slopeCV:0.137},
        {name:'D6',freq:1174.66,loopPts:[0.69921,0.86905,1.03467,1.20535,1.37605,1.5459,1.70644,1.8822,2.05204,2.21766,2.38751,2.55819,2.72381,2.89365],trimStart:0.0035,slopeCV:0.122},
        {name:'E6',freq:1318.51,loopPts:[0.74458,0.92018,1.09578,1.27066,1.44626,1.62562,1.80122,1.9776,2.1532,2.33333,2.50367,2.68379,2.85939],trimStart:0.0083,slopeCV:0.107},
        {name:'G6',freq:1567.98,loopPts:[0.9432,1.11857,1.3095,1.49467,1.67984,1.86567,2.05594,2.24177,2.42694,2.61211,2.79728,2.98757],trimStart:0.007,slopeCV:0.237},
        {name:'Bb6',freq:1864.66,loopPts:[1.10138,1.26138,1.4171,1.57281,1.72746,1.888,2.04372,2.19943,2.35943,2.51515,2.6698,2.82551,2.98605],trimStart:0.0047,slopeCV:0.215},
        {name:'C7',freq:2093,loopPts:[0.84694,0.9871,1.12726,1.26313,1.40329,1.54297,1.68361,1.82376,1.96392,2.10456,2.24472,2.38059,2.52075,2.66138,2.80107,2.94122],trimStart:0.0056,slopeCV:0.2}
      ]
    },
    cello:{
      name:'Cello',baseUrl:'https://gleitz.github.io/midi-js-soundfonts/FluidR3_GM/cello-mp3/',
      ext:'.mp3',releaseTime:0.3,volume:1.0,loop:true,decays:false,vibrato:true,
      /* Generated by the vibrato-aware analyzer (prepareLoopVibrato, AMP mode
         with correlation-based waveform-phase snapping). */
      samples:[
        {name:'G2',freq:98,loopPts:[0.95002,1.15458,1.35893,1.56331,1.76769,1.97206,2.17644,2.38082,2.58522,2.78957],trimStart:0.0089,slopeCV:0.106},
        {name:'A2',freq:110,loopPts:[0.84379,1.03522,1.21728,1.39937,1.58145,1.76351,1.94562,2.12766,2.30975,2.49184,2.67388,2.85594],trimStart:0.0081,slopeCV:0.089},
        {name:'Db3',freq:138.59,loopPts:[0.87238,1.07456,1.27673,1.47896,1.6883,1.89052,2.09272,2.28776,2.48998,2.69218,2.90154],trimStart:0.0052,slopeCV:0.252},
        {name:'E3',freq:164.81,loopPts:[0.92395,1.10615,1.2944,1.48265,1.66483,1.85916,2.04741,2.23565,2.4239,2.61215,2.80041],trimStart:0.0076,slopeCV:0.073},
        {name:'G3',freq:196,loopPts:[1.3946,1.60932,1.82401,2.03871,2.25853,2.68286,2.89755],trimStart:0.012,slopeCV:0.085},
        {name:'Bb3',freq:233.08,loopPts:[1.32333,1.53791,1.75678,1.97567,2.19451,2.41336,2.63227,2.85111],trimStart:0.0028,slopeCV:0.084},
        {name:'Db4',freq:277.18,loopPts:[1.68698,1.8678,2.04864,2.22948,2.41392,2.59113,2.77197,2.95279],trimStart:0.0041,slopeCV:0.108},
        {name:'E4',freq:329.63,loopPts:[1.18522,1.38503,1.57873,1.76338,1.95714,2.14782,2.34463,2.53533,2.72907,2.92587],trimStart:0.0024,slopeCV:0.167},
        {name:'G4',freq:392,loopPts:[1.39909,1.58531,1.75624,1.93227,2.11084,2.29195,2.82766,3.00624],trimStart:0.0027,slopeCV:1.149},
        {name:'Bb4',freq:466.16,loopPts:[1.1698,1.36522,1.55635,1.74961,1.93642,2.13404,2.32084,2.51195,2.70524,2.8942],trimStart:0.0028,slopeCV:0.079},
        {name:'Db5',freq:554.37,loopPts:[0.41007,0.5907,0.95689,1.14315,1.3258,1.51385,1.69111,1.87916,2.06181,2.24807,2.43615,2.62059,2.79964,2.9859],trimStart:0.0096,slopeCV:0.378},
        {name:'Eb5',freq:622.25,loopPts:[0.84782,1.01859,1.18293,1.34726,1.50998,1.67431,1.83864,2.00458,2.1641,2.33002,2.49596,2.66029,2.82782,2.98735],trimStart:0.0062,slopeCV:0.361},
        {name:'G5',freq:783.99,loopPts:[1.31082,1.6917,2.07889,2.27186,2.85077],trimStart:0.0032,slopeCV:0.472},
        {name:'Bb5',freq:932.33,loopPts:[1.18995,1.38621,1.58571,1.78522,1.98147,2.18206,2.38154,2.57889,2.7773,2.97465],trimStart:0.0028,slopeCV:0.259},
        {name:'C6',freq:1046.5,loopPts:[1.05932,1.23512,1.41095,1.58964,1.76642,1.94222,2.12188,2.29673,2.47349,2.64739,2.828],trimStart:0.0027,slopeCV:0.242},
        {name:'E6',freq:1318.51,loopPts:[0.63941,0.85474,1.19088,1.38113,1.56649,1.74161,1.91748,2.09789,2.27302,2.44889,2.62476,2.80442,2.98029],trimStart:0.0089,slopeCV:0.323},
        {name:'G6',freq:1567.98,loopPts:[0.3581,0.54299,0.71392,0.99912,1.16417,1.31558,1.46537,1.61073,1.76116,1.91095,2.0563,2.20739,2.35272,2.50317,2.65361,2.8034,2.94875],trimStart:0.0078,slopeCV:0.296},
        {name:'A6',freq:1760,loopPts:[0.63732,0.88857,1.03846,1.16937,1.30397,1.43515,1.56519,1.6998,1.83098,1.96558,2.09562,2.22624,2.36141,2.49145,2.62721,2.75782,2.89299],trimStart:0.0071,slopeCV:0.273},
        {name:'B6',freq:1975.53,loopPts:[0.56694,0.67263,0.79279,0.92329,1.04295,1.1583,1.27873,1.39864,1.51399,1.63442,1.74977,1.86968,1.98503,2.10596,2.22082,2.34073,2.45608,2.57701,2.69186,2.81177,2.92712],trimStart:0.0064,slopeCV:0.242}
      ]
    },
    trombone:{
      name:'Trombone',baseUrl:'https://gleitz.github.io/midi-js-soundfonts/FluidR3_GM/trombone-mp3/',
      ext:'.mp3',releaseTime:0.25,volume:1.0,loop:true,decays:false,
      /* 14 samples, Ab2 to Bb5. Generated by macro-period analyzer with the
         v0.8 amplitude-step gate (rmsStepThreshold=0.08) added on top of the
         standard clique threshold. Trombone has gradual breath-pressure
         envelope drift across each sample's 3s duration, so loop pairs drawn
         from temporally-distant endpoints can have phase-coherent but
         volume-mismatched signals. cliqueThreshold alone missed this — the
         new gate rejects pairs where |envRmsA - envRmsB|/max > 8% using a
         50ms-window envelope RMS. Effect vs prior run: earliest (buildup-
         phase) loop point dropped from most samples; E5 dropped entirely
         (high-drift); F5 and Bb5 added (extended upper range). */
      samples:[
        {name:'Ab2',freq:103.784,loopPts:[0.9843764,1.2445125,1.5142857,1.7648073,2.0249433,2.2947166,2.5645125,2.8149887],validStartsByEnd:[[],[0],[0,1],[0,1,2],[0,1,2,3],[0,1,2,3,4],[0,1,2,3,4,5],[0,1,2,3,4,5,6]],trimStart:0.0170522},
        {name:'B2',freq:123.38,loopPts:[0.8940816,1.1696372,1.4452154,1.7126757,1.988254,2.2638095,2.5393878,2.8068481],validStartsByEnd:[[],[0],[0,1],[0,1,2],[0,1,2,3],[0,1,2,3,4],[0,1,2,3,4,5],[0,1,2,3,4,5,6]],trimStart:0.0066893},
        {name:'D3',freq:146.729,loopPts:[0.8966893,1.1624943,1.4419274,1.700907,1.9735147,2.2529478,2.5119274,2.7913605],validStartsByEnd:[[],[0],[0,1],[0,1,2],[0,1,2,3],[0,1,2,3,4],[0,1,2,3,4,5],[0,1,2,3,4,5,6]],trimStart:0.0069388},
        {name:'F3',freq:174.496,loopPts:[0.6239229,0.9333787,1.2428571,1.546576,1.8560544,2.1655102,2.474966,2.7787075],validStartsByEnd:[[],[0],[0,1],[0,1,2],[0,1,2,3],[0,1,2,3,4],[0,1,2,3,4,5],[0,1,2,3,4,5,6]],trimStart:0.0076644},
        {name:'Ab3',freq:207.529,loopPts:[0.4178231,0.7792063,1.1068934,1.4345578,1.7670522,2.0947166,2.4272109,2.754898],validStartsByEnd:[[],[0],[0,1],[0,1,2],[0,1,2,3],[0,1,2,3,4],[0,1,2,3,4,5],[0,1,2,3,4,5,6]],trimStart:0.0113152},
        {name:'B3',freq:246.951,loopPts:[0.3651474,0.7053288,1.0454875,1.3856689,1.7258503,2.0619728,2.4021542,2.7423129],validStartsByEnd:[[],[0],[0,1],[0,1,2],[0,1,2,3],[0,1,2,3,4],[0,1,2,3,4,5],[0,1,2,3,4,5,6]],trimStart:0.0091837},
        {name:'D4',freq:293.669,loopPts:[0.4026077,0.7362812,1.0768254,1.4105215,1.7476417,2.0881859,2.4253061,2.7590023],validStartsByEnd:[[],[0],[0,1],[0,1,2],[0,1,2,3],[0,1,2,3,4],[0,1,2,3,4,5],[0,1,2,3,4,5,6]],trimStart:0.004966},
        {name:'F4',freq:349.032,loopPts:[0.2700227,0.6252834,0.9662358,1.3243991,1.6854195,2.0406803,2.3959637,2.7455102],validStartsByEnd:[[],[0],[0,1],[0,1,2],[0,1,2,3],[0,1,2,3,4],[0,1,2,3,4,5],[0,1,2,3,4,5,6]],trimStart:0.0070295},
        {name:'Ab4',freq:415.057,loopPts:[0.2294785,0.5860544,0.9570975,1.3112925,1.6678685,2.0389116,2.3882766,2.737619],validStartsByEnd:[[],[0],[0,1],[0,1,2],[0,1,2,3],[0,1,2,3,4],[0,1,2,3,4,5],[0,1,2,3,4,5,6]],trimStart:0.0103401},
        {name:'B4',freq:493.442,loopPts:[0.1813152,0.5440363,0.9088209,1.2715873,1.6363946,1.999161,2.3619274,2.7267347],validStartsByEnd:[[],[0],[0,1],[0,1,2],[0,1,2,3],[0,1,2,3,4],[0,1,2,3,4,5],[0,1,2,3,4,5,6]],trimStart:0.0092744},
        {name:'D5',freq:586.812,loopPts:[0.1530612,0.4358957,0.809093,1.2624036,1.6185941,1.9798866,2.2900227,2.6530159],validStartsByEnd:[[],[0],[0,1],[0,1,2],[0,1,2,3],[0,1,2,3,4],[0,1,2,3,4,5],[0,1,2,3,4,5,6]],trimStart:0.0067347},
        {name:'Gb5',freq:739.235,loopPts:[0.1831746,0.5808163,0.9270975,1.2760317,1.6331293,1.976712,2.3594785,2.7246939],validStartsByEnd:[[],[0],[0,1],[0,1,2],[0,1,2,3],[0,1,2,3,4],[0,1,2,3,4,5],[0,1,2,3,4,5,6]],trimStart:0.0056689}
    ],
    },
    flute:{
      name:'Flute',baseUrl:'https://gleitz.github.io/midi-js-soundfonts/FluidR3_GM/flute-mp3/',
      ext:'.mp3',releaseTime:0.2,volume:1.0,loop:true,decays:false,vibrato:true,
      /* Generated by the vibrato-aware analyzer (prepareLoopVibrato, AMP mode).
         Every loop point sits at both a positive-going waveform zero crossing
         AND a positive-going amplitude-modulation zero crossing, with
         consistent vibrato period (~3-8 Hz across the range). Any two of these
         points can be paired as a loop segment and the boundary will be
         seamless in both fundamental waveform and tremolo phase. */
      samples:[
        {name:'C4',freq:261.63,loopPts:[0.82476,1.05739,1.32043,1.60635,1.85796,2.12483,2.40311,2.66236,2.92159],trimStart:0.0154,slopeCV:0.076},
        {name:'Eb4',freq:311.13,loopPts:[0.58358,0.84329,1.09989,1.36286,1.6322,1.8888,2.15177,2.41794,2.67771,2.94388],trimStart:0.005,slopeCV:0.34},
        {name:'Gb4',freq:369.99,loopPts:[0.76819,0.99741,1.23741,1.47741,1.73088,1.95741,2.19741,2.44551,2.68281,2.92011],trimStart:0.0128,slopeCV:0.192},
        {name:'A4',freq:440,loopPts:[0.49694,0.7781,1.02077,1.28837,1.55594,1.819,2.07526,2.34059,2.61497,2.85989],trimStart:0.0062,slopeCV:0.09},
        {name:'B4',freq:493.88,loopPts:[0.44288,0.68127,0.92168,1.14392,1.37828,1.62878,1.85304,2.08134,2.31569,2.57224,2.78644],trimStart:0.0057,slopeCV:0.088},
        {name:'Eb5',freq:622.25,loopPts:[1.01893,1.24161,1.47234,1.92093,2.14846,2.37757],trimStart:0.0034,slopeCV:0.089},
        {name:'G5',freq:783.99,loopPts:[0.44426,0.70914,0.96637,1.22107,1.48086,1.75336,2.00297,2.26404,2.53399,2.77977],trimStart:0.004,slopeCV:0.098},
        {name:'A5',freq:880,loopPts:[0.3937,0.62966,0.86905,1.09027,1.32172,1.55542,1.79141,2.01152,2.24748,2.488,2.7149,2.93955],trimStart:0.0037,slopeCV:0.094},
        {name:'Db6',freq:1108.73,loopPts:[0.85088,1.16603,1.5163,1.86297,2.20333,2.56982,2.89488],trimStart:0.0044,slopeCV:0.108},
        {name:'E6',freq:1318.51,loopPts:[0.6968,0.98302,1.26771,1.56907,1.85376,2.13998,2.44134,2.7215],trimStart:0.016,slopeCV:0.1},
        {name:'Gb6',freq:1479.98,loopPts:[0.61488,0.89077,1.13159,1.38658,1.66653,1.90735,2.16302,2.43351,2.68984,2.94011],trimStart:0.0141,slopeCV:0.097},
        {name:'A6',freq:1760,loopPts:[0.51501,0.7402,0.95633,1.16621,1.38177,1.61263,1.82308,2.03295,2.25361,2.48506,2.69039,2.90594],trimStart:0.0146,slopeCV:0.09},
        {name:'C7',freq:2093,loopPts:[0.4276,0.61265,0.81299,0.98424,1.1593,1.34485,1.52991,1.72596,1.89052,2.07655,2.25637,2.45243,2.63272,2.80825,2.98807],trimStart:0.0123,slopeCV:0.083},
        {name:'Eb7',freq:2489.02,loopPts:[0.3622,0.51222,0.67265,0.84313,0.98311,1.12871,1.28433,1.43916,1.6,1.75562,1.90043,2.05084,2.20646,2.36129,2.67254,2.81735,2.97297],trimStart:0.012,slopeCV:0.076},
        {name:'Gb7',freq:2959.96,loopPts:[0.43163,0.56215,0.69707,0.95746,1.07821,1.20839,1.33859,1.46406,1.60404,1.73961,1.86002,1.97977,2.11063,2.24082,2.37068,2.63646,2.75687,2.88739],trimStart:0.0113,slopeCV:0.068},
        {name:'A7',freq:3520,loopPts:[0.3595,0.46955,0.58016,0.69531,0.92079,1.0158,1.12132,1.23163,1.34168,1.44719,1.56744,1.78782,1.88283,1.98834,2.09839,2.20871,2.31875,2.64946,2.74986,2.86048,2.97052],trimStart:0.0095,slopeCV:0.056},
        {name:'B7',freq:3951.07,loopPts:[0.41646,0.51703,0.61204,0.71714,1.00268,1.09794,1.1932,1.28846,1.38372,1.48404,1.78977,1.87492,1.96488,2.06544,2.1607,2.25596,2.35576,2.65671,2.74186,2.83712,2.93238],trimStart:0.0063,slopeCV:0.047}
      ]
    },
    drawbar_organ:{
      name:'Drawbar Organ',baseUrl:'https://gleitz.github.io/midi-js-soundfonts/FatBoy/drawbar_organ-mp3/',
      ext:'.mp3',releaseTime:0.15,volume:1.0,loop:true,decays:false,vibrato:true,
      /* Hammond drawbar convention: filenames label pitches an octave above
         the actual recorded audio content. transpose=2.0 plays back at 2× the
         filename-derived rate so a key requesting 440 Hz audibly produces 440 Hz. */
      transpose:2.0,
      /* 25 samples, diminished-7th sampling (every minor third: B, D, F, Ab)
         from B1 to B7. Generated via the vibrato-aware analyzer path (manually
         enabled — drawbar organ has enough harmonic chorusing that the vibrato
         detector locks on and produces dense valid-seam graphs). FatBoy source
         avoids the multi-rank detuning warble that plagued the FluidR3 church
         organ. Filter params (analyzer defaults): rmsGate=0.08, specGate=1.5,
         cliqueThreshold=0.25, minSpacing=50ms, minBackward=150ms,
         minForward=300ms, xfade=30ms. */
      samples:[
        {name:'B1',freq:61.74,loopPts:[0.51193,1.06127,1.61093,2.32229,2.87193],validStartsByEnd:[[],[0],[0,1],[0,1,2],[0,1,2,3]],trimStart:0.0005,slopeCV:0.298},
        {name:'D2',freq:73.42,loopPts:[0.4307,0.89268,1.35485,1.95304,2.41524],validStartsByEnd:[[],[0],[0,1],[0,1,2],[0,1,2,3]],trimStart:0.0007,slopeCV:0.275},
        {name:'F2',freq:87.31,loopPts:[0.73658,1.12535,1.62825,2.01703,2.51991,2.90868],validStartsByEnd:[[],[0],[0,1],[0,1,2],[0,1,2,3],[0,1,2,3,4]],trimStart:0,slopeCV:0.274},
        {name:'Ab2',freq:103.83,loopPts:[0.63889,0.96585,1.38871,1.71565,2.1385,2.46544,2.8883],validStartsByEnd:[[],[0],[0,1],[0,1,2],[0,1,2,3],[0,1,2,3,4],[0,1,2,3,4,5]],trimStart:0.0001,slopeCV:0.258},
        {name:'B2',freq:123.47,loopPts:[0.53748,0.81243,1.16798,1.44293,1.7985,2.07342,2.42898,2.70395],validStartsByEnd:[[],[0],[0,1],[0,1,2],[0,1,2,3],[0,1,2,3,4],[0,1,2,3,4,5],[0,1,2,3,4,5,6]],trimStart:0.0001,slopeCV:0.237},
        {name:'D3',freq:146.83,loopPts:[0.44707,0.67816,0.97726,1.20834,1.50744,1.73853,2.03764,2.26873,2.56782,2.79891],validStartsByEnd:[[],[0],[0,1],[0,1,2],[0,1,2,3],[0,1,2,3,4],[0,1,2,3,4,5],[0,1,2,3,4,5,6],[0,1,2,3,4,5,6,7],[0,1,2,3,4,5,6,7,8]],trimStart:0,slopeCV:0.213},
        {name:'F3',freq:174.61,loopPts:[0.38048,0.5749,0.82633,1.02073,1.27215,1.46655,1.71798,1.9124,2.16381,2.35823,2.60964,2.80406],validStartsByEnd:[[],[0],[0,1],[0,1,2],[0,1,2,3],[0,1,2,3,4],[0,1,2,3,4,5],[0,1,2,3,4,5,6],[0,1,2,3,4,5,6,7],[0,1,2,3,4,5,6,7,8],[0,1,2,3,4,5,6,7,8,9],[0,1,2,3,4,5,6,7,8,9,10]],trimStart:0,slopeCV:0.192},
        {name:'Ab3',freq:207.65,loopPts:[0.701,1.0759,1.45079,1.82569,2.20059,2.57549,2.95041],validStartsByEnd:[[],[0],[0,1],[0,1,2],[0,1,2,3],[0,1,2,3,4],[0,1,2,3,4,5]],trimStart:0,slopeCV:0.169},
        {name:'B3',freq:246.94,loopPts:[0.58472,0.90805,1.22331,1.53855,1.85381,2.16907,2.47624,2.79957],validStartsByEnd:[[],[0],[0,1],[0,1,2],[0,1,2,3],[0,1,2,3,4],[0,1,2,3,4,5],[0,1,2,3,4,5,6]],trimStart:0,slopeCV:0.123},
        {name:'D4',freq:293.66,loopPts:[0.50288,0.76796,1.03306,1.29814,1.56324,1.82834,2.09345,2.35853,2.62363,2.88873],validStartsByEnd:[[],[0],[0,1],[0,1,2],[0,1,2,3],[0,1,2,3,4],[0,1,2,3,4,5],[0,1,2,3,4,5,6],[0,1,2,3,4,5,6,7],[0,1,2,3,4,5,6,7,8]],trimStart:0.0001,slopeCV:0.106},
        {name:'F4',freq:349.23,loopPts:[0.42533,0.64823,0.87116,1.09408,1.31698,1.53989,1.76281,1.98571,2.20864,2.43156,2.65449,2.87741],validStartsByEnd:[[],[0],[0,1],[0,1,2],[0,1,2,3],[0,1,2,3,4],[0,1,2,3,4,5],[0,1,2,3,4,5,6],[0,1,2,3,4,5,6,7],[0,1,2,3,4,5,6,7,8],[0,1,2,3,4,5,6,7,8,9],[0,1,2,3,4,5,6,7,8,9,10]],trimStart:0,slopeCV:0.063},
        {name:'Ab4',freq:415.3,loopPts:[0.36651,0.52537,0.67946,0.84311,1.00195,1.15603,1.31966,1.47853,1.63739,1.79147,1.9551,2.11397,2.26805,2.43168,2.59054,2.74463,2.90825],validStartsByEnd:[[],[0],[0,1],[0,1,2],[0,1,2,3],[0,1,2,3,4],[0,1,2,3,4,5],[0,1,2,3,4,5,6],[0,1,2,3,4,5,6,7],[0,1,2,3,4,5,6,7,8],[0,1,2,3,4,5,6,7,8,9],[0,1,2,3,4,5,6,7,8,9,10],[0,1,2,3,4,5,6,7,8,9,10,11],[0,1,2,3,4,5,6,7,8,9,10,11,12],[0,1,2,3,4,5,6,7,8,9,10,11,12,13],[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14],[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]],trimStart:0,slopeCV:0.106},
        {name:'B4',freq:493.88,loopPts:[0.44202,0.5756,0.70517,0.84277,0.97635,1.10592,1.24351,1.37308,1.50667,1.64426,1.77785,1.90744,2.04503,2.17859,2.30816,2.44576,2.57934,2.70893,2.84653,2.98011],validStartsByEnd:[[],[0],[0,1],[0,1,2],[0,1,2,3],[0,1,2,3,4],[0,1,2,3,4,5],[0,1,2,3,4,5,6],[0,1,2,3,4,5,6,7],[0,1,2,3,4,5,6,7,8],[0,1,2,3,4,5,6,7,8,9],[0,1,2,3,4,5,6,7,8,9,10],[0,1,2,3,4,5,6,7,8,9,10,11],[0,1,2,3,4,5,6,7,8,9,10,11,12],[0,1,2,3,4,5,6,7,8,9,10,11,12,13],[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14],[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16],[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17],[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18]],trimStart:0,slopeCV:0.092},
        {name:'D5',freq:587.33,loopPts:[0.42961,0.5758,0.72202,0.86478,1.01098,1.15717,1.3068,1.44617,1.59918,1.74197,1.88816,2.03438,2.18057,2.32336,2.47637,2.61916,2.76535,2.91156],validStartsByEnd:[[],[0],[0,1],[0,1,2],[0,1,2,3],[0,1,2,3,4],[0,1,2,3,4,5],[0,1,2,3,4,5,6],[0,1,2,3,4,5,6,7],[0,1,2,3,4,5,6,7,8],[0,1,2,3,4,5,6,7,8,9],[0,1,2,3,4,5,6,7,8,9,10],[0,1,2,3,4,5,6,7,8,9,10,11],[0,1,2,3,4,5,6,7,8,9,10,11,12],[0,1,2,3,4,5,6,7,8,9,10,11,12,13],[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14],[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]],trimStart:0,slopeCV:0.059},
        {name:'F5',freq:698.46,loopPts:[0.3615,0.48154,0.60449,0.72456,0.85036,0.97043,1.09624,1.2163,1.34211,1.46218,1.58798,1.71381,1.83385,1.95966,2.07973,2.20553,2.32562,2.44855,2.57147,2.69442,2.81449,2.94029],validStartsByEnd:[[],[0],[0,1],[0,1,2],[0,1,2,3],[0,1,2,3,4],[0,1,2,3,4,5],[0,1,2,3,4,5,6],[0,1,2,3,4,5,6,7],[0,1,2,3,4,5,6,7,8],[0,1,2,3,4,5,6,7,8,9],[0,1,2,3,4,5,6,7,8,9,10],[0,1,2,3,4,5,6,7,8,9,10,11],[0,1,2,3,4,5,6,7,8,9,10,11,12],[0,1,2,3,4,5,6,7,8,9,10,11,12,13],[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14],[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16],[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17],[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18],[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19],[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]],trimStart:0,slopeCV:0.05},
        {name:'Ab5',freq:830.61,loopPts:[0.36395,0.51057,0.65472,0.79404,0.94063,1.08481,1.23141,1.37798,1.52215,1.65902,1.80565,1.94982,2.09639,2.23571,2.38472,2.52889,2.67306,2.81723,2.95898],validStartsByEnd:[[],[0],[0,1],[0,1,2],[0,1,2,3],[0,1,2,3,4],[0,1,2,3,4,5],[0,1,2,3,4,5,6],[0,1,2,3,4,5,6,7],[0,1,2,3,4,5,6,7,8],[0,1,2,3,4,5,6,7,8,9],[0,1,2,3,4,5,6,7,8,9,10],[0,1,2,3,4,5,6,7,8,9,10,11],[0,1,2,3,4,5,6,7,8,9,10,11,12],[0,1,2,3,4,5,6,7,8,9,10,11,12,13],[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14],[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16],[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17]],trimStart:0,slopeCV:0.103},
        {name:'B5',freq:987.77,loopPts:[0.42753,0.55079,0.67406,0.79528,0.92059,1.03773,1.15694,1.2802,1.40143,1.64186,1.76104,1.88431,2.00351,2.1288,2.24596,2.37127,2.48841,2.61372,2.73293,2.85415,2.97333],validStartsByEnd:[[],[0],[0,1],[0,1,2],[0,1,2,3],[0,1,2,3,4],[0,1,2,3,4,5],[0,1,2,3,4,5,6],[0,1,2,3,4,5,6,7],[0,1,2,3,4,5,6,7,8],[0,1,2,3,4,5,6,7,8,9],[0,1,2,3,4,5,6,7,8,9,10],[0,1,2,3,4,5,6,7,8,9,10,11],[0,1,2,3,4,5,6,7,8,9,10,11,12],[0,1,2,3,4,5,6,7,8,9,10,11,12,13],[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14],[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16],[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17],[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18],[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]],trimStart:0,slopeCV:0.071},
        {name:'D6',freq:1174.66,loopPts:[0.43542,0.61052,0.78052,0.9522,1.12732,1.2973,1.46728,1.63728,1.80896,1.98408,2.15406,2.32404,2.49574,2.67082,2.84082],validStartsByEnd:[[],[0],[0,1],[0,1,2],[0,1,2,3],[0,1,2,3,4],[0,1,2,3,4,5],[0,1,2,3,4,5,6],[0,1,2,3,4,5,6,7],[0,1,2,3,4,5,6,7,8],[0,1,2,3,4,5,6,7,8,9],[0,1,2,3,4,5,6,7,8,9,10],[0,1,2,3,4,5,6,7,8,9,10,11],[0,1,2,3,4,5,6,7,8,9,10,11,12],[0,1,2,3,4,5,6,7,8,9,10,11,12,13]],trimStart:0,slopeCV:0.038},
        {name:'F6',freq:1396.91,loopPts:[0.36553,0.51134,0.65571,0.80152,0.94732,1.08741,1.23179,1.3776,1.5234,1.66778,1.8093,1.95367,2.09948,2.24526,2.38964,2.53544,2.68125,2.82134,2.96571],validStartsByEnd:[[],[0],[0,1],[0,1,2],[0,1,2,3],[0,1,2,3,4],[0,1,2,3,4,5],[0,1,2,3,4,5,6],[0,1,2,3,4,5,6,7],[0,1,2,3,4,5,6,7,8],[0,1,2,3,4,5,6,7,8,9],[0,1,2,3,4,5,6,7,8,9,10],[0,1,2,3,4,5,6,7,8,9,10,11],[0,1,2,3,4,5,6,7,8,9,10,11,12],[0,1,2,3,4,5,6,7,8,9,10,11,12,13],[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14],[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16],[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17]],trimStart:0.0003,slopeCV:0.034},
        {name:'Ab6',freq:1661.22,loopPts:[0.43039,0.70107,0.97172,1.23757,1.50222,1.77288,2.03873,2.30941,2.58007,2.84592],validStartsByEnd:[[],[0],[0,1],[0,1,2],[0,1,2,3],[0,1,2,3,4],[0,1,2,3,4,5],[0,1,2,3,4,5,6],[0,1,2,3,4,5,6,7],[0,1,2,3,4,5,6,7,8]],trimStart:0,slopeCV:0.098},
        {name:'B6',freq:1975.53,loopPts:[0.36011,0.58569,0.81127,1.03685,1.26243,1.488,1.71358,1.93916,2.16372,2.3893,2.61488,2.84045],validStartsByEnd:[[],[0],[0,1],[0,1,2],[0,1,2,3],[0,1,2,3,4],[0,1,2,3,4,5],[0,1,2,3,4,5,6],[0,1,2,3,4,5,6,7],[0,1,2,3,4,5,6,7,8],[0,1,2,3,4,5,6,7,8,9],[0,1,2,3,4,5,6,7,8,9,10]],trimStart:0,slopeCV:0.093},
        {name:'D7',freq:2349.32,loopPts:[0.49052,0.68107,0.87159,1.06213,1.25181,1.43726,1.6278,1.81832,2.00887,2.19941,2.38995,2.58048,2.77102,2.9607],validStartsByEnd:[[],[0],[0,1],[0,1,2],[0,1,2,3],[0,1,2,3,4],[0,1,2,3,4,5],[0,1,2,3,4,5,6],[0,1,2,3,4,5,6,7],[0,1,2,3,4,5,6,7,8],[0,1,2,3,4,5,6,7,8,9],[0,1,2,3,4,5,6,7,8,9,10],[0,1,2,3,4,5,6,7,8,9,10,11],[0,1,2,3,4,5,6,7,8,9,10,11,12]],trimStart:0,slopeCV:0.087},
        {name:'F7',freq:2793.83,loopPts:[0.41029,0.5705,0.73073,0.89168,1.0519,1.21211,1.37234,1.52755,1.68848,1.84871,2.00893,2.16916,2.32438,2.48531,2.64553,2.80576,2.96599],validStartsByEnd:[[],[0],[0,1],[0,1,2],[0,1,2,3],[0,1,2,3,4],[0,1,2,3,4,5],[0,1,2,3,4,5,6],[0,1,2,3,4,5,6,7],[0,1,2,3,4,5,6,7,8],[0,1,2,3,4,5,6,7,8,9],[0,1,2,3,4,5,6,7,8,9,10],[0,1,2,3,4,5,6,7,8,9,10,11],[0,1,2,3,4,5,6,7,8,9,10,11,12],[0,1,2,3,4,5,6,7,8,9,10,11,12,13],[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14],[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]],trimStart:0,slopeCV:0.078},
        {name:'Ab7',freq:3322.44,loopPts:[0.34506,0.48039,0.61571,0.75107,0.88639,1.15224,1.28696,1.42231,1.55281,1.82349,1.95882,2.08934,2.22406,2.35941,2.48991,2.63007,2.76059,2.89592],validStartsByEnd:[[],[0],[0,1],[0,1,2],[0,1,2,3],[0,1,2,3,4],[0,1,2,3,4,5],[0,1,2,3,4,5,6],[0,1,2,3,4,5,6,7],[0,1,2,3,4,5,6,7,8],[0,1,2,3,4,5,6,7,8,9],[0,1,2,3,4,5,6,7,8,9,10],[0,1,2,3,4,5,6,7,8,9,10,11],[0,1,2,3,4,5,6,7,8,9,10,11,12],[0,1,2,3,4,5,6,7,8,9,10,11,12,13],[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14],[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]],trimStart:0,slopeCV:0.069},
        {name:'B7',freq:3951.07,loopPts:[0.52052,0.97168,1.08193,1.19726,1.30751,1.42234,1.53259,1.64791,1.75816,1.87349,1.98374,2.09907,2.20932,2.32465,2.4349,2.55023,2.66048,2.7758,2.88605],validStartsByEnd:[[],[0],[0,1],[0,1,2],[0,1,2,3],[0,1,2,3,4],[0,1,2,3,4,5],[0,1,2,3,4,5,6],[0,1,2,3,4,5,6,7],[0,1,2,3,4,5,6,7,8],[0,1,2,3,4,5,6,7,8,9],[0,1,2,3,4,5,6,7,8,9,10],[0,1,2,3,4,5,6,7,8,9,10,11],[0,1,2,3,4,5,6,7,8,9,10,11,12],[0,1,2,3,4,5,6,7,8,9,10,11,12,13],[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14],[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16],[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17]],trimStart:0,slopeCV:0.055}
      ]
    },
    reed_organ:{
      name:'Reed Organ',baseUrl:'https://gleitz.github.io/midi-js-soundfonts/FatBoy/reed_organ-mp3/',
      ext:'.mp3',releaseTime:0.15,volume:1.0,loop:true,decays:false,
      /* 27 samples, chromatic coverage from C1 to C7 (extends half an octave
         below drawbar). Generated via the macro-period path with STRICT gate
         overrides — the only HKL instrument currently using non-default filter
         parameters. Reed organ produced abundant candidates; strict gates
         pruned per-seam for maximum loop quality. Filter params (strict):
         rmsGate=0.05 (from 0.08), specGate=1.0 (from 1.5),
         cliqueThreshold=0.15 (from 0.25 — tightest seam-midpoint-RMS filter;
         only near-phase-coherent loop pairs accepted), minSpacing=75ms (from
         50ms), minBackward=150ms, minForward=300ms, xfade=30ms. Several samples
         (B3, D5, C6, D6, E6, C7) have individually-pruned entries in
         validStartsByEnd where specific loop points had no clean backward
         partner. This is intentional — drop bad seams, keep good ones. */
      samples:[
        {name:'Db1',freq:34.708,loopPts:[1.6805215,1.8533107,2.0261224,2.1989796,2.3718367,2.515941,2.6888209,2.861678],validStartsByEnd:[[],[0],[0,1],[0,1,2],[0,1,2,3],[0,1,2,3],[0,1,2,3,4,5],[0,1,2,3,4,5,6]],trimStart:0.0085261},
        {name:'E1',freq:41.277,loopPts:[1.6627664,1.832381,2.0019955,2.1715873,2.3653968,2.5349887,2.7045805,2.8741723],validStartsByEnd:[[],[0],[0,1],[0,1,2],[0,1,2,3],[0,1,2,3,4],[0,1,2,3,4,5],[0,1,2,3,4,5,6]],trimStart:0.0100907},
        {name:'G1',freq:49.07,loopPts:[1.4738776,1.6775964,1.8813379,2.0646939,2.2683673,2.4720408,2.675805,2.859229],validStartsByEnd:[[],[0],[0,1],[0,1,2],[0,1,2,3],[0,1,2,3,4],[0,1,2,3,4,5],[0,1,2,3,4,5,6]],trimStart:0.0087755},
        {name:'Bb1',freq:58.367,loopPts:[1.6272109,1.8156463,1.9869388,2.1753741,2.3466893,2.5351247,2.7064172,2.8948753],validStartsByEnd:[[],[0],[0,1],[0,1,2],[0,1,2,3],[0,1,2,3,4],[0,1,2,3,4,5],[0,1,2,3,4,5,6]],trimStart:0.0077324},
        {name:'Db2',freq:69.429,loopPts:[1.6278231,1.815102,1.9879592,2.1752154,2.3480952,2.5353741,2.708254,2.8955329],validStartsByEnd:[[],[0],[0,1],[0,1,2],[0,1,2,3],[0,1,2,3,4],[0,1,2,3,4,5],[0,1,2,3,4,5,6]],trimStart:0.0068254},
        {name:'E2',freq:82.548,loopPts:[0.4363265,0.7270748,1.0178231,1.3085034,1.599229,1.93839,2.2291383,2.5198866],validStartsByEnd:[[],[0],[0,1],[0,1,2],[0,1,2,3],[0,1,2,3,4],[0,1,2,3,4,5],[0,1,2,3,4,5,6]],trimStart:0.0076644},
        {name:'G2',freq:98.162,loopPts:[0.4995692,0.7236961,0.9579592,1.1820408,1.4163265,1.6404308,1.8645125,2.0988209],validStartsByEnd:[[],[0],[0,1],[0,1,2],[0,1,2,3],[0,1,2,3,4],[0,1,2,3,4,5],[0,1,2,3,4,5,6]],trimStart:0.0075737},
        {name:'Bb2',freq:116.772,loopPts:[1.4171429,1.5285034,1.5884807,1.6569841,1.7255102,1.7854649,1.8540136,1.9140136],validStartsByEnd:[[],[],[0],[0],[0,1],[0,1,2],[0,1,2,3],[0,1,2,3,4]],trimStart:0.0066667},
        {name:'D3',freq:147.11,loopPts:[2.2760544,2.6703855,2.7723583,2.8811338,2.9830839],validStartsByEnd:[[],[0],[0],[0,1],[0,1,2]],trimStart:0.0085714},
        {name:'Gb3',freq:185.328,loopPts:[2.270907,2.4975283,2.6702041,2.7565306,2.8428571],validStartsByEnd:[[],[0],[0,1],[0,1],[0,1,2]],trimStart:0.0071655},
        {name:'Bb3',freq:233.506,loopPts:[1.1152154,2.8240136,2.9010884,2.9781859],validStartsByEnd:[[],[0],[0],[0,1]],trimStart:0.0073016},
        {name:'Db4',freq:277.659,loopPts:[0.4757596,1.4589796,1.8407256,2.4997506,2.8634921],validStartsByEnd:[[],[0],[0,1],[0,1,2],[0,1,2,3]],trimStart:0.0063946},
        {name:'E4',freq:330.007,loopPts:[0.2691837,0.4237868,0.5146939,0.8389342,0.9298186,1.0631746,1.5509977],validStartsByEnd:[[],[0],[0],[0,1,2],[0,1,2],[0,1,2,3],[0,1,2,3,4,5]],trimStart:0.0066213},
        {name:'A4',freq:440.803,loopPts:[0.8162132,0.9590703,1.3765079,1.5285261,1.7122676,2.3520635],validStartsByEnd:[[],[],[0,1],[0,1,2],[0,1,2,3],[0,1,2,3,4]],trimStart:0.0069841},
        {name:'C5',freq:524.152,loopPts:[0.5282086,1.1901814,1.6251247,2.1001814,2.559932,2.884263],validStartsByEnd:[[],[0],[0,1],[0,1,2],[0,1,2,3],[0,1,2,3,4]],trimStart:0.0061224},
        {name:'E5',freq:660.456,loopPts:[2.5999773,2.6892971,2.7529025,2.8180272,2.8816327,2.9452154,3.0148753],validStartsByEnd:[[],[],[0],[0],[0,1],[0,1,2],[0,1,2,3]],trimStart:0.0054875},
        {name:'Ab5',freq:831.985,loopPts:[0.1194785,0.458458,0.8022449,1.1328571,1.4633787,1.8252381,2.2002721,2.6102041],validStartsByEnd:[[],[0],[0,1],[0,1,2],[0,1,2,3],[0,1,2,3,4],[0,1,2,3,4,5],[0,1,2,3,4,5,6]],trimStart:0.0060091},
        {name:'B5',freq:989.277,loopPts:[0.0643084,0.8577778,1.2236961,1.5896372,1.9545578,2.3629025],validStartsByEnd:[[],[0],[0,1],[0,1,2],[0,1,2,3],[0,1,2,3,4]],trimStart:0.0050113},
        {name:'D6',freq:1176.56,loopPts:[1.0836281,1.3190476,1.79678,2.1971429,2.3773469,2.8397279],validStartsByEnd:[[],[0],[0,1],[0,1,2],[0,1,2,3],[0,1,2,3,4]],trimStart:0.0061224},
        {name:'Gb6',freq:1482.056,loopPts:[0.7686621,1.5815873,1.9621088,2.1489796],validStartsByEnd:[[],[0],[0,1],[0,1,2]],trimStart:0.0058277}
      ]
    },
    harp:{
      name:'Harp',baseUrl:'https://gleitz.github.io/midi-js-soundfonts/FluidR3_GM/orchestral_harp-mp3/',
      ext:'.mp3',releaseTime:0.5,volume:1.0,loop:false,decays:true,
      samples:[
        {name:'C2',freq:65.41},{name:'Eb2',freq:77.78},{name:'Gb2',freq:92.5},
        {name:'A2',freq:110},{name:'C3',freq:130.81},{name:'Eb3',freq:155.56},
        {name:'Gb3',freq:185},{name:'A3',freq:220},{name:'C4',freq:261.63},
        {name:'Eb4',freq:311.13},{name:'Gb4',freq:369.99},{name:'A4',freq:440},
        {name:'C5',freq:523.25},{name:'Eb5',freq:622.25},{name:'Gb5',freq:739.99},
        {name:'A5',freq:880},{name:'C6',freq:1046.5},{name:'Eb6',freq:1244.51}
      ]
    }
  };
  var ctx: any = null, master: any = null, sampleMaster: any = null, buffers: Record<string, any> = {}, activeVoices: Record<string, any> = {}, currentInstrument: any = null;
  function init(audioCtx: AudioContext, destNode: AudioNode): void {
    ctx=audioCtx;
    /* samples get their own master gain, independent of oscillator oscGain/squareGain */
    sampleMaster=ctx.createGain();
    sampleMaster.gain.value=1.0;
    sampleMaster.connect(destNode);
    master=sampleMaster;
  }
  function loadInstrument(key: string, onProgress?: (loaded: number, total: number, name: string) => void): Promise<void> {
    return new Promise<void>(function(resolve,reject){
      var instr=INSTRUMENTS[key];
      if(!instr)return reject(new Error('Unknown instrument: '+key));
      if(buffers[key]){currentInstrument=key;return resolve();}
      var loaded=0,total=instr.samples.length,result: any[] = [];
      var aborted=false;
      function logLoopReport(){
        console.log('=== Loop points for '+instr.name+' ===');
        var tableRows: any[] = [];
        for(var i=0;i<result.length;i++){
          var r=result[i];if(!r)continue;
          var pts=r.lp&&r.lp.loopPts;
          if(!pts||pts.length<2){
            var failRow: any = {sample:instr.samples[i].name,freq:r.freq,count:pts?pts.length:0,
              span_ms:'-',min_gap_ms:'-',max_gap_ms:'-',mean_gap_ms:'-'};
            if(r.lp&&r.lp.stats&&!r.lp.stats.precomputed){
              failRow.slopeCV=r.lp.stats.slopeCV||'-';
              failRow.crossings=r.lp.stats.crossings||'-';
              failRow.candidates=r.lp.stats.candidates||'-';
              failRow.correlated=r.lp.stats.correlated||'-';
              failRow.failReason=r.lp.stats.failReason||'-';
            }
            tableRows.push(failRow);
            continue;
          }
          var gaps=[];
          for(var j=1;j<pts.length;j++)gaps.push((pts[j]-pts[j-1])*1000);
          var span=(pts[pts.length-1]-pts[0])*1000;
          var minG=Math.min.apply(null,gaps),maxG=Math.max.apply(null,gaps);
          var meanG=gaps.reduce(function(a: number, b: number){return a+b;},0)/gaps.length;
          var row: any = {
            sample:instr.samples[i].name,freq:r.freq,
            count:pts.length,
            span_ms:Math.round(span),
            min_gap_ms:Math.round(minG),
            max_gap_ms:Math.round(maxG),
            mean_gap_ms:Math.round(meanG),
            slopeCV:r.lp.slopeCV!==undefined?(typeof r.lp.slopeCV==='number'?r.lp.slopeCV.toFixed(3):r.lp.slopeCV):'-'
          };
          /* Only show runtime-analysis stats for samples that weren't precomputed */
          if(r.lp.stats&&!r.lp.stats.precomputed){
            row.crossings=r.lp.stats.crossings;
            row.candidates=r.lp.stats.candidates;
            row.correlated=r.lp.stats.correlated;
            row.corr_thresh=r.lp.stats.corrThresh;
          }
          tableRows.push(row);
        }
        console.table(tableRows);
      }
      instr.samples.forEach(function(s: any, i: number){
        if(aborted)return;
        var url=instr.baseUrl+s.name+instr.ext;
        var timer=setTimeout(function(){aborted=true;delete buffers[key];reject(new Error("Timeout loading "+s.name));},10000);
        fetch(url).then(function(r){
          if(!r.ok)throw new Error('HTTP '+r.status);return r.arrayBuffer();
        }).then(function(ab){return ctx.decodeAudioData(ab);}).then(function(buf){
          clearTimeout(timer);if(aborted)return;
          var lp;
          if(instr.loop&&s.loopPts){
            /* Trust the precomputed loop points as-is. The analyzer runs in
               the browser via decodeAudioData, so its points are already
               sample-aligned to the browser's decoded audio. HKL loads the
               same MP3 through the same decoder and gets identical samples;
               re-snapping would only introduce noise by picking a different
               nearby crossing as a tiebreaker. Decoder drift could matter
               across different browsers (Firefox analyzer → Chromium HKL),
               but even then, moving by ±1-2 samples doesn't fix a true
               decoder mismatch and is just as likely to hurt as help.

               validStartsByEnd / endsByStart pass through by reference — they
               are the analyzer's seam-validity graph, read-only at runtime,
               and absolutely required by scheduleSegmentSwitch. Dropping them
               sends the picker into the legacy random branch, which produces
               forward / same-point jumps and ignores the analyzer's work.

               Snap loopPts and trimStart to integer audio samples here. The
               paste-output rounded these to a few decimal places, which loses
               sub-sample precision (e.g., trimStart=0.0094 round-trips to
               414.54 samples instead of 414). At rate=1 a fractional offset
               forces buffer-read interpolation everywhere it propagates; if
               the FIRST source's offset (trimStart) has a different fractional
               part than every SUBSEQUENT source's offset (pts[a]), the two
               sources read the buffer at different sub-sample positions during
               a crossfade — producing an audibly different timbre on the first
               switch despite identical buffer-content endpoints. Snapping
               normalizes both to the integer grid so for rate=1 every source
               reads buffer at integer samples and there's nothing to interpolate. */
            var sr=buf.sampleRate;
            var snappedTrim=Math.round((s.trimStart||0)*sr)/sr;
            var snappedPts=s.loopPts.map(function(p: number){return Math.round(p*sr)/sr;});
            lp={trimStart:snappedTrim,loopPts:snappedPts,slopeCV:s.slopeCV||0,
                validStartsByEnd:s.validStartsByEnd,endsByStart:s.endsByStart,
                stats:{precomputed:true,count:s.loopPts.length}};
          } else if(instr.loop){
            /* No runtime fallback — the analyzer must produce loopPts for any
               loop-mode instrument we ship. Failing loud here surfaces a data
               problem at load time, which is far better than silently shipping
               an instrument with no working loops. To regenerate, open
               tools/HexKeyLab-analyzer.html, analyze the affected sample(s),
               and paste the loopPts/validStartsByEnd into samples.ts. */
            var msg='SampleEngine: instrument "'+key+'" sample "'+s.name+'" is loop-mode but has no precomputed loopPts. Re-run the analyzer for this sample.';
            console.error(msg);
            aborted=true;
            delete buffers[key];
            reject(new Error(msg));
            return;
          } else {
            lp={trimStart:0};
          }
          /* trim silence for decaying instruments too */
          if(!instr.loop){var _d=buf.getChannelData(0);for(var _s=0;_s<buf.length;_s++){if(Math.abs(_d[_s])>0.003){lp.trimStart=_s/buf.sampleRate;break;}}}
          result[i]={buffer:buf,freq:s.freq,lp:lp,name:s.name};loaded++;
          if(onProgress)onProgress(loaded,total,s.name);
          if(loaded===total&&!aborted){
            buffers[key]=result.filter(function(x){
              if(x===null)return false;
              /* for looping instruments, exclude samples that failed to produce loop points */
              if(instr.loop&&(!x.lp||!x.lp.loopPts))return false;
              return true;
            });
            currentInstrument=key;resolve();
          }
        }).catch(function(err){
          clearTimeout(timer);if(aborted)return;
          result[i]=null;loaded++;console.warn('Failed to load '+s.name+':',err);
          if(onProgress)onProgress(loaded,total,s.name+' \u2717');
          if(loaded===total&&!aborted){
            buffers[key]=result.filter(function(x){
              if(x===null)return false;
              if(instr.loop&&(!x.lp||!x.lp.loopPts))return false;
              return true;
            });
            if(buffers[key].length===0){delete buffers[key];reject(new Error('All samples failed'));}
            else{currentInstrument=key;resolve();}}
        });
      });
    });
  }
  function findNearest(freq: number): any {
    var samps=buffers[currentInstrument];if(!samps||samps.length===0)return null;
    var best=0,bestDist=Infinity;
    for(var i=0;i<samps.length;i++){var dist=Math.abs(Math.log2(freq/samps[i].freq));if(dist<bestDist){bestDist=dist;best=i;}}
    return samps[best];
  }
  /* Range attenuation: pure function of frequency (no state). Returns gain factor
     for a given frequency — 1.0 within range, reducing toward 0.5 as freq exceeds
     the highest sample. Used identically by sNoteOn and sNoteOnFaded so that
     transposing up and back down fully restores the original gain. */
  function rangeAttenuation(freq: number): number {
    var samps=buffers[currentInstrument];
    if(!samps||samps.length===0)return 1.0;
    var highestFreq=samps[samps.length-1].freq;
    if(freq<=highestFreq)return 1.0;
    var overshoot=freq/highestFreq; /* 1.0 at top, 1.5 = fifth up, 2.0 = octave up */
    /* gentle taper: 1.0 → 1.0, 1.5 → 0.82, 2.0 → 0.64, ≥2.4 → 0.5 (clamped) */
    return Math.max(0.5,1.0-(overshoot-1.0)*0.36);
  }
  function sNoteOn(voiceKey: string, freq: number, velocity: number): void {
    if(!ctx||!currentInstrument)return;
    if(activeVoices[voiceKey])sNoteOff(voiceKey);
    var nearest=findNearest(freq);if(!nearest)return;
    var instr=INSTRUMENTS[currentInstrument];
    var rate=freq*(instr.transpose||1)/nearest.freq;
    var vel=(velocity!==undefined)?velocity/127:0.85;
    var instrVol=instr.volume||1.0;
    var baseVol=(0.10+0.90*vel*vel)*instrVol;
    /* ── ABOVE-RANGE VIBRATO ATTENUATION ──
       When a note is requested above the highest sampled pitch, the sample gets
       pitch-shifted up — which also speeds up its vibrato (cello's ~5Hz vibrato
       at rate=1.68× becomes ~8.4Hz, sounds unnatural). We can't slow the vibrato
       without Melodyne-style time-stretching, but reducing overall gain makes the
       vibrato less prominent in proportion to its speed. Pure function of frequency
       (not stateful) so that transposing up and back down fully restores gain. */
    var vol=baseVol*rangeAttenuation(freq);
    /* pressureGain: modulated by polyphonic aftertouch. Initialized to 1.0 so
       the note plays at its velocity-driven volume until the first aftertouch
       message arrives (which may be never, or well after onset). Placed outside
       voiceGain so it doesn't interfere with the release envelope. */
    var pressureGain=ctx.createGain();pressureGain.gain.value=1.0;pressureGain.connect(master);
    /* damperGain: continuous-damper modulation. Sits between voiceGain (release
       envelope) and pressureGain (aftertouch) — engine.ts ramps it via
       setVoiceDamperDepth while the key is in sustainedKeys, pins to 1.0 for
       sostenuto-locked keys. Default 1.0 = no attenuation. */
    var damperGain=ctx.createGain();damperGain.gain.value=1.0;damperGain.connect(pressureGain);
    /* voiceGain: persistent node for this voice — noteOff fades this to silence everything */
    var voiceGain=ctx.createGain();voiceGain.gain.value=1.0;voiceGain.connect(damperGain);
    var segGain=ctx.createGain();
    /* Schedule the source FIRST_SOURCE_LEAD seconds in the future, not at
       currentTime, and record sourceStartTime as the same future moment.
       Reason: source.start(t, ...) with t < ctx.currentTime gets clamped by
       Web Audio to the actual currentTime at processing — which can be one
       render quantum (~2.7ms) or more past `t` if JS stalls between
       capturing currentTime and the audio thread consuming the schedule.
       Recording sourceStartTime as the JS-captured time then under-records
       the actual start moment, throwing off the switchTime computation in
       scheduleSegmentSwitch. The mismatch produces a phase-shifted crossfade
       on the first switch that the analyzer never validated → audible dip.
       Pre-scheduling far enough ahead makes start exact (no clamping). The
       lead must comfortably exceed any plausible JS stall on the note-on
       path (event handler, click logic, redraw, possible GC pause) — 50ms
       is well above the worst case while still imperceptible (≪100ms) as
       note-onset latency. Subsequent sources (created in scheduleSegmentSwitch)
       already pre-schedule with even more lead; this brings the first source
       in line. */
    /* Snap to the next integer audio sample so every source we ever start
       has a sample-aligned `when`. Combined with sample-aligned offsets
       (trimStart / pts[a] are snapped at sample-load time), this means at
       rate=1 the audio engine reads the buffer at integer sample positions
       throughout — no interpolation, and identical sub-sample alignment
       across the first source and every subsequent source. */
    var startT=Math.ceil((ctx.currentTime+0.050)*ctx.sampleRate)/ctx.sampleRate;
    segGain.gain.setValueAtTime(vol,startT);
    var source=ctx.createBufferSource();source.buffer=nearest.buffer;
    source.playbackRate.value=rate;
    var pts=nearest.lp&&nearest.lp.loopPts;
    /* Read the jump graph. New field: validStartsByEnd[b] = list of valid
       backward-jump targets a < b with clean seam and ≥minBackwardSec distance.
       Legacy field: endsByStart[a] = list of forward ends. We convert the
       legacy format on the fly so old sample data still works. */
    var vsbe=nearest.lp&&nearest.lp.validStartsByEnd;
    if(!vsbe&&nearest.lp&&nearest.lp.endsByStart){
      /* Legacy conversion: invert endsByStart[a]=[b,...] into validStartsByEnd[b]=[a,...] */
      var legacyEBS=nearest.lp.endsByStart;
      vsbe=new Array(pts.length);
      for(var li=0;li<pts.length;li++)vsbe[li]=[];
      for(var la=0;la<legacyEBS.length;la++){
        var bs=legacyEBS[la]||[];
        for(var lk=0;lk<bs.length;lk++){
          var lb=bs[lk];
          if(lb>la&&lb<pts.length)vsbe[lb].push(la);
        }
      }
    }
    /* NO source.loop=true — we handle ALL looping via scheduleSegmentSwitch.
       The browser's native loop causes hard-cut wraps that click regardless
       of how close pts[a] and pts[b] are at the ZC+slope level (harmonic
       phase relationships still differ). Instead, scheduleSegmentSwitch
       fires a timer just before each wrap would occur, crossfades to a
       fresh source starting at the new pts[a], and stops the old source.
       If a timer fires late (rare), the old source plays forward past
       pts[b] into whatever audio follows — a natural fade-out into the
       sample's decay tail or silence rather than a click. */
    /* Still set loopStart/loopEnd so sourceOffset/wrap-time math is documented
       via these values, but loop=false means the browser doesn't act on them. */
    if(instr.loop&&pts&&pts.length>=2){
      source.loopStart=pts[0];source.loopEnd=pts[pts.length-1];
    }
    source.connect(segGain);segGain.connect(voiceGain);
    var startOffset=(nearest.lp&&nearest.lp.trimStart)?nearest.lp.trimStart:0;
    source.start(startT,startOffset);
    var voice={source:source,segGain:segGain,voiceGain:voiceGain,damperGain:damperGain,pressureGain:pressureGain,freq:freq,sampleFreq:nearest.freq,transpose:(instr.transpose||1),sampleName:nearest.name,
      vol:vol,baseVol:baseVol,alive:true,loopPts:pts,validStartsByEnd:vsbe,loopTimer:null,buffer:nearest.buffer,instr:instr,
      slopeCV:(nearest.lp&&typeof nearest.lp.slopeCV==='number')?nearest.lp.slopeCV:0.5,
      /* ── SOURCE ANCHOR (for wrap-aligned segment switching) ──
         Tracks the current source's loop state as both time positions
         (sourceLoopA/B) and loop-point indices (sourceLoopAIdx/BIdx). The
         sourceLoopBIdx is what scheduleSegmentSwitch uses to look up valid
         backward-jump targets via validStartsByEnd[sourceLoopBIdx]. Time
         positions drive the wrap-scheduler math:
           firstWrap = sourceStartTime + (sourceLoopB - sourceOffset) / sourceRate
         The initial source's loop spans the entire pts array, so
         sourceLoopAIdx=0, sourceLoopBIdx=pts.length-1.
         sourceStartTime is the FUTURE startT scheduled above — never the
         JS-captured currentTime — so wrap-scheduler math matches reality. */
      sourceStartTime:startT,sourceOffset:startOffset,
      sourceLoopA:(pts&&pts.length>=2)?pts[0]:0,
      sourceLoopB:(pts&&pts.length>=2)?pts[pts.length-1]:0,
      sourceLoopAIdx:0,
      sourceLoopBIdx:(pts&&pts.length>=2)?pts.length-1:0,
      sourceRate:rate};
    source.onended=function(){voice.alive=false;};
    activeVoices[voiceKey]=voice;
    if(instr.loop&&pts&&pts.length>=2){
      /* Play through to the last loop point before the first switch —
         gives ~1-3s of pristine sustain before any crossfade artifacts
         can occur. scheduleSegmentSwitch reads source-anchor state for
         the first-wrap time, so no initial-delay arg is needed. */
      scheduleSegmentSwitch(voiceKey);
    }
  }
  /* Pick (a, b) for the NEXT loop segment, given the current voice state
     (specifically v.sourceLoopBIdx — the b we're jumping FROM). Logic shared
     between scheduleSegmentSwitch (pre-schedule path) and doImmediateSwitch
     (synchronous path) so both honor validStartsByEnd identically.

     ═══ Pick new pair (a_new, b_new) ═══
     TWO-STEP PROCESS with correct runtime separation of concerns:

     1. BACKWARD JUMP: we're at pts[b_cur] and need to jump backward to
        some a_new < b_cur where the seam is clean and the jump is
        meaningful (≥minBackwardSec distance). The clean-seam-candidates
        are pre-computed in validStartsByEnd[b_cur] — at analysis time
        the filter verified each a→b_cur crossfade and rejected pairs
        with audible phase-mismatch artifacts.

     2. FORWARD ENDPOINT: once a_new is chosen, b_new can be any point
        where pts[b_new] - pts[a_new] ≥ minForwardSec. No seam is
        involved here — it's just playing forward through the sample.
        The only requirement is that the loop segment is long enough to
        not churn (≥minForwardSec). */
  function pickNextSeam(v: any, pts: any): {a: number, b: number} {
    var vsbeLocal=v.validStartsByEnd;
    var bCurIdx=v.sourceLoopBIdx;
    var a:number=0,b:number=pts.length-1;
    if(pts.length===2){return {a:0,b:1};}
    if(!vsbeLocal){
      /* Legacy sample data without the graph — generate pairs on the fly.
         Constrain a < bCurIdx so we never produce a forward or same-point
         jump (the original implementation ignored bCurIdx, which manifested
         as audible "loop ran out faster" and unvalidated seams). */
      var minJumpSec=0.20,pairFound=false;
      for(var at=0;at<100;at++){
        if(bCurIdx<=0){a=0;b=pts.length-1;pairFound=true;break;}
        a=Math.floor(Math.random()*bCurIdx);
        b=a+1+Math.floor(Math.random()*(pts.length-a-1));
        if(b>=pts.length)b=pts.length-1;
        if(pts[b]-pts[a]>=minJumpSec){pairFound=true;break;}
      }
      if(!pairFound){a=0;b=pts.length-1;}
      return {a:a,b:b};
    }
    /* STEP 1: pick a_new uniformly from validStartsByEnd[bCurIdx] */
    var aCands=(bCurIdx<vsbeLocal.length&&vsbeLocal[bCurIdx])?vsbeLocal[bCurIdx]:[];
    if(aCands.length===0){
      /* No valid backward jump from current b. This can happen if the
         graph has empty validStartsByEnd[b] for the current b (dead-end
         endpoint). Keep the current pair — we'll re-loop until some
         other state change picks a new b. */
      return {a:v.sourceLoopAIdx,b:v.sourceLoopBIdx};
    }
    a=aCands[Math.floor(Math.random()*aCands.length)];
    /* STEP 2: pick b_new from points where the forward segment
       (pts[b_new] - pts[a]) is ≥ minForwardSec. Must also have b_new
       as a "live" endpoint (reachable via some future backward jump)
       — a live endpoint is one where validStartsByEnd[b_new] is
       nonempty. Otherwise we could land on a dead-end b and get stuck.
       We also allow b_new = last loop point regardless (we can always
       fall through to that, even if the future switch has to keep
       the same pair). */
    var minForwardSec=0.30;
    var bCands:number[]=[];
    for(var bi=a+1;bi<pts.length;bi++){
      if(pts[bi]-pts[a]<minForwardSec)continue;
      var isLive=(bi<vsbeLocal.length&&vsbeLocal[bi]&&vsbeLocal[bi].length>0);
      if(isLive||bi===pts.length-1)bCands.push(bi);
    }
    if(bCands.length===0){
      /* No forward partner. Pick any valid b_new≥a_new+1 as fallback. */
      for(var bi2=a+1;bi2<pts.length;bi2++)bCands.push(bi2);
    }
    if(bCands.length===0){return {a:v.sourceLoopAIdx,b:v.sourceLoopBIdx};}
    b=bCands[Math.floor(Math.random()*bCands.length)];
    return {a:a,b:b};
  }

  /* ── WRAP-ALIGNED SEGMENT SWITCHING (every wrap is a switch) ──
     ALL looping is handled here — no browser-native loop is engaged. Each
     source plays a single pass through its [loopStart, loopEnd] segment,
     then is replaced at the pts[b] moment with a new source using a new
     (a, b) pair and a 30ms linear crossfade.

     Why no native-loop safety net: the browser's native loop produces a
     hard-cut wrap from loopEnd back to loopStart. Even with ZC+slope
     matching, the instantaneous harmonic phase configuration differs
     between those two points (macro-period samples match by spectral
     shape over a window, not sample-perfect), so the hard cut clicks.
     Crossfading over that click doesn't help because the click is in
     the OLD source's own output, not at the seam between old and new.

     ── PRE-SCHEDULE ON THE AUDIO CLOCK ──
     Critical: the crossfade audio events are scheduled HERE, at the moment
     scheduleSegmentSwitch is called, anchored exactly at switchTime — not
     in a setTimeout body that runs near switchTime. Web Audio scheduling
     is sample-accurate; setTimeout firing time is not. Anchoring on the
     audio clock makes the crossfade deterministic regardless of JS
     event-loop jitter (which would otherwise let the old source play past
     pts[b_old] into unvalidated buffer content for tens of ms before the
     ramp-out started — the source of intermittent same-seam dips).

     setTimeout's only job is JS-side state cleanup (commitPendingSwitch +
     re-schedule the next switch). Late firing is harmless because the
     audio has already played. cancelPendingSwitch undoes the pre-scheduled
     events if a rate ramp interrupts before commit.

     Relies on source-anchor state (sourceStartTime, sourceOffset,
     sourceLoopA, sourceLoopB, sourceRate) being accurate. Set by sNoteOn
     for initial source, by commitPendingSwitch for subsequent sources, and
     by sRampFreq after playbackRate ramps settle. */
  function scheduleSegmentSwitch(voiceKey: string, _initialDelayMs?: number): void {
    var v=activeVoices[voiceKey];
    if(!v||!v.alive||!v.loopPts||v.loopPts.length<2)return;
    /* Defensive: a stray pre-scheduled switch shouldn't exist here, but if
       it does (e.g., from a missed cancel path), tear it down before
       creating a new one to avoid double-stacking sources. */
    if(v.pendingSwitch)cancelPendingSwitch(v);
    var pts=v.loopPts;
    var rate=v.sourceRate||v.source.playbackRate.value||1;
    var now=ctx.currentTime;
    /* The current source wraps at this time. ALWAYS switch at every wrap. */
    var switchTime=v.sourceStartTime+(v.sourceLoopB-v.sourceOffset)/rate;
    /* If we're already past the wrap (extreme JS stall during a prior call),
       push a few ms forward so setValueAtTime / source.start are valid. */
    if(switchTime<now+0.005)switchTime=now+0.005;

    var picked=pickNextSeam(v,pts);
    var a=picked.a,b=picked.b;

    /* ── 30ms LINEAR CROSSFADE ──
       Old source at pts[b_old] (just reached its loopEnd), new source
       starts at pts[a_new]. Linear ramp gives amplitude = |cos(Δφₖ/2)| at
       midpoint per harmonic — no +3dB boost at phase-aligned fundamental
       (equal-power would do that). Empirically settled on 30ms with the
       current engine; never benchmarked against alternatives. */
    var xfDur=0.030;
    var newSrc=ctx.createBufferSource();newSrc.buffer=v.buffer;
    /* No newSrc.loop=true — the next scheduleSegmentSwitch will replace this
       source before it reaches pts[b]. loopStart/loopEnd are metadata only. */
    newSrc.loopStart=pts[a];newSrc.loopEnd=pts[b];
    newSrc.playbackRate.value=v.source.playbackRate.value;
    var newSG=ctx.createGain();
    newSG.gain.setValueAtTime(0,switchTime);
    newSG.gain.linearRampToValueAtTime(v.vol,switchTime+xfDur);
    newSrc.connect(newSG);newSG.connect(v.voiceGain);
    newSrc.start(switchTime,pts[a]);

    /* Pre-schedule the OLD source's gain ramp out at switchTime. Crucially,
       do NOT schedule oldSrc.stop() yet — stop() is one-shot and uncancellable,
       so deferring it to commitPendingSwitch keeps cancellation symmetric.

       Anchor the ramp at v.vol (the known steady-state level), not at
       oldSegGain.gain.value. The .value getter races with future-scheduled
       setValueAtTime events: when scheduleSegmentSwitch runs immediately
       after sNoteOn (which schedules vol at startT, 5ms in the future),
       audio time hasn't reached startT yet so .value still reads the
       AudioParam default of 1.0 — which would force an audible amplitude
       boost at switchTime if used here. v.vol is the source of truth. */
    var oldSrc=v.source,oldSegGain=v.segGain;
    oldSegGain.gain.cancelScheduledValues(switchTime);
    oldSegGain.gain.setValueAtTime(v.vol,switchTime);
    oldSegGain.gain.linearRampToValueAtTime(0,switchTime+xfDur);

    /* Capture old b idx for the seam-event log at commit time. */
    v.pendingSwitch={
      newSrc:newSrc,newSG:newSG,oldSrc:oldSrc,oldSegGain:oldSegGain,
      switchTime:switchTime,xfDur:xfDur,a:a,b:b,fromBIdx:v.sourceLoopBIdx
    };

    /* JS-only timer: fires after the crossfade completes, with a small
       margin. Late firing is harmless. */
    var commitTimerMs=Math.max(0,(switchTime+xfDur-now)*1000)+5;
    v.loopTimer=setTimeout(function(){
      commitPendingSwitch(voiceKey);
      scheduleSegmentSwitch(voiceKey);
    },commitTimerMs);
  }

  /* Commit a pre-scheduled switch: advance JS-side voice state to the new
     source, schedule old-source cleanup, and emit the seam diagnostic event.
     Audio has already played its crossfade on the audio clock; this just
     reconciles JS state with the new reality. */
  function commitPendingSwitch(voiceKey: string): void {
    var v=activeVoices[voiceKey];
    if(!v||!v.pendingSwitch)return;
    var p=v.pendingSwitch;
    var pts=v.loopPts;
    /* Schedule old source's stop now (its gain ramped to 0 at switchTime+xfDur). */
    try{p.oldSrc.stop(p.switchTime+p.xfDur+0.02);}catch(e){}
    p.oldSrc.onended=function(){
      try{p.oldSrc.disconnect();}catch(e){}
      try{p.oldSegGain.disconnect();}catch(e){}
    };
    /* Advance voice state to the new source. */
    v.source=p.newSrc;v.segGain=p.newSG;
    v.sourceStartTime=p.switchTime;
    v.sourceOffset=pts[p.a];
    v.sourceLoopA=pts[p.a];v.sourceLoopB=pts[p.b];
    v.sourceLoopAIdx=p.a;v.sourceLoopBIdx=p.b;
    v.sourceRate=p.newSrc.playbackRate.value;
    recordSeamEvent({ctxTime:p.switchTime,voiceKey:voiceKey,sampleName:v.sampleName||'?',
      rate:v.sourceRate||1,fromBIdx:p.fromBIdx,toAIdx:p.a,
      fromTime:pts[p.fromBIdx],toTime:pts[p.a],xfadeDur:p.xfDur});
    p.newSrc.onended=function(){v.alive=false;};
    v.pendingSwitch=null;
  }

  /* Cancel a pre-scheduled switch (called from sRampFreq/sNoteOff/sHardStop
     before they mutate v.source). Stops the new source, disconnects its
     graph, and restores the old segGain to v.vol via a brief 5ms ramp so
     mid-crossfade cancellation doesn't click. */
  function cancelPendingSwitch(v: any): void {
    if(!v.pendingSwitch)return;
    var p=v.pendingSwitch;
    /* stop(0) clamps to currentTime per spec — works whether newSrc has
       already started (cancel after switchTime) or not (cancel before). */
    try{p.newSrc.stop(0);}catch(e){}
    try{p.newSrc.disconnect();}catch(e){}
    try{p.newSG.disconnect();}catch(e){}
    var now=ctx.currentTime;
    p.oldSegGain.gain.cancelScheduledValues(now);
    p.oldSegGain.gain.setValueAtTime(p.oldSegGain.gain.value,now);
    p.oldSegGain.gain.linearRampToValueAtTime(v.vol,now+0.005);
    v.pendingSwitch=null;
  }
    function sNoteOff(voiceKey: string): void {
    var v=activeVoices[voiceKey];if(!v)return;
    if(v.loopTimer){clearTimeout(v.loopTimer);v.loopTimer=null;}
    if(v.reAnchorTimer){clearTimeout(v.reAnchorTimer);v.reAnchorTimer=null;}
    /* If a switch was pre-scheduled but not yet committed, tear it down so the
       new source doesn't continue playing (silently, behind the released
       voiceGain) and leak the BufferSource node. */
    if(v.pendingSwitch)cancelPendingSwitch(v);
    var instr=INSTRUMENTS[currentInstrument];
    var release=(((instr&&instr.releaseTime)||0.3)*RELEASE_SCALE);var now=ctx.currentTime;
    if(v.alive){
      /* fade voiceGain — silences ALL sources routed through it */
      v.voiceGain.gain.cancelScheduledValues(now);
      v.voiceGain.gain.setValueAtTime(v.voiceGain.gain.value,now);
      v.voiceGain.gain.linearRampToValueAtTime(0,now+release);
      try{v.source.stop(now+release+0.05);}catch(e){}
    }
    delete activeVoices[voiceKey];
  }
  /* Execute a segment switch SYNCHRONOUSLY and return immediately with all
     voice state updated. Unlike scheduleSegmentSwitch (which schedules a
     future setTimeout), this creates the new source and advances the voice
     state right now. The new source starts playing `startTime` seconds in
     the future (default: immediate + tiny lead), crossfading in over the
     same window the scheduled switches use. Used by sRampFreq to close the
     wrap-during-ramp coverage gap.
     
     Returns true on success, false if voice state can't support a switch. */
  function doImmediateSwitch(voiceKey: string, startTime?: number): boolean {
    var v=activeVoices[voiceKey];
    if(!v||!v.alive||!v.loopPts||v.loopPts.length<2)return false;
    var pts=v.loopPts;
    if(pts.length<2)return false;
    /* If a pre-scheduled switch is in flight, tear it down — we're about to
       create a different new source synchronously, and the pending one would
       layer on top and corrupt voice state. */
    if(v.pendingSwitch)cancelPendingSwitch(v);
    var bCurIdx=v.sourceLoopBIdx;
    var now=ctx.currentTime;
    var st: number = startTime===undefined?now+0.008:startTime;
    var picked=pickNextSeam(v,pts);
    var a=picked.a,b=picked.b;
    /* Create new source, crossfade, update voice state. */
    var xfDur=0.030;
    var newSrc=ctx.createBufferSource();newSrc.buffer=v.buffer;
    newSrc.loopStart=pts[a];newSrc.loopEnd=pts[b];
    newSrc.playbackRate.value=v.source.playbackRate.value;
    var newSG=ctx.createGain();
    newSG.gain.setValueAtTime(0,st);
    newSG.gain.linearRampToValueAtTime(v.vol,st+xfDur);
    newSrc.connect(newSG);newSG.connect(v.voiceGain);
    newSrc.start(st,pts[a]);
    var oldSource=v.source,oldSegGain=v.segGain;
    /* Anchor the ramp at v.vol — same rationale as scheduleSegmentSwitch:
       reading oldSegGain.gain.value can race with future-scheduled events. */
    oldSegGain.gain.cancelScheduledValues(st);
    oldSegGain.gain.setValueAtTime(v.vol,st);
    oldSegGain.gain.linearRampToValueAtTime(0,st+xfDur);
    oldSource.onended=function(){
      try{oldSource.disconnect();}catch(e){}
      try{oldSegGain.disconnect();}catch(e){}
    };
    try{oldSource.stop(st+xfDur+0.02);}catch(e){}
    /* Update voice state to reference the new source — anchor for future
       wrap computation is (st, pts[a], newRate). */
    v.source=newSrc;v.segGain=newSG;
    v.sourceStartTime=st;
    v.sourceOffset=pts[a];
    v.sourceLoopA=pts[a];v.sourceLoopB=pts[b];
    v.sourceLoopAIdx=a;v.sourceLoopBIdx=b;
    v.sourceRate=newSrc.playbackRate.value;
    recordSeamEvent({ctxTime:st,voiceKey:voiceKey,sampleName:v.sampleName||'?',
      rate:v.sourceRate||1,fromBIdx:bCurIdx,toAIdx:a,fromTime:pts[bCurIdx],toTime:pts[a],xfadeDur:xfDur});
    newSrc.onended=function(){v.alive=false;};
    return true;
  }
  /* ══ commitRampSync ══
     Synchronously advance the voice's anchor to time `now`, correctly
     handling an in-flight rate ramp. Necessary when a new sRampFreq fires
     while a prior ramp's re-anchor setTimeout is still pending — without
     this, the prior re-anchor runs with stale ramp parameters (its ramp
     was cancelled by the new one) and corrupts anchor state, which
     compounds across rapid transposes ("multiple octaves and back").

     Math: the pending ramp goes r0→r1 linearly over [rs, re]. Position
     integral from rs to min(now, re) is (r0+rateAtT)/2 * dt. Post-ramp
     (now > re) adds r1 * (now - re). Anchor is updated to this moment,
     with the current instantaneous rate.

     We do NOT fold position into [loopA, loopB] here. During a ramp the
     audio source plays forward without native looping, so the actual
     playhead IS at the unfolded position; if it exceeds loopB, the
     wrap-during-ramp check downstream must handle it via doImmediateSwitch.
     Folding would desync the anchor from reality. */
  function commitRampSync(v: any, now: number): void {
    if(v.pendingRampStart===undefined)return;
    var rs=v.pendingRampStart,re=v.pendingRampEnd;
    var r0=v.pendingRampR0,r1=v.pendingRampR1;
    /* Position at rs assuming constant r0 since the previous anchor — this
       is the invariant the anchor was set to maintain. */
    var posAtRs=v.sourceOffset+r0*(rs-v.sourceStartTime);
    var rt=(now<re)?now:re;
    var dt=rt-rs;
    var rampDur=re-rs;
    var rateAtRt=(dt<=0)?r0:(r0+(r1-r0)*(dt/rampDur));
    var advance=(r0+rateAtRt)*0.5*dt;
    var posAtRt=posAtRs+advance;
    if(now>re)posAtRt+=r1*(now-re);
    v.sourceStartTime=now;
    v.sourceOffset=posAtRt;
    v.sourceRate=(now<re)?rateAtRt:r1;
    v.pendingRampStart=undefined;
    v.pendingRampEnd=undefined;
    v.pendingRampR0=undefined;
    v.pendingRampR1=undefined;
  }
  function sRampFreq(voiceKey: string, newFreq: number, durSec: number): boolean {
    var v=activeVoices[voiceKey];if(!v)return false;
    if(!v.alive){var pv=v.vol;delete activeVoices[voiceKey];sNoteOn(voiceKey,newFreq,Math.round(((pv-0.3)/0.7)*127));return true;}
    var now=ctx.currentTime;
    /* ── COMMIT ANY IN-FLIGHT RAMP ──
       If a prior ramp's re-anchor setTimeout is still pending, cancel it
       and commit the prior ramp's state up to `now` synchronously. This
       prevents the stale-snapshot race where the prior re-anchor would
       fire later with ramp parameters that no longer reflect reality
       (its ramp is about to be cancelled by our cancelScheduledValues). */
    if(v.reAnchorTimer){
      clearTimeout(v.reAnchorTimer);
      v.reAnchorTimer=null;
      commitRampSync(v,now);
    }
    /* Cancel any pre-scheduled segment switch — its audio events were anchored
       on the old rate and pre-ramp state, which is about to change. The
       reAnchorTimer below will schedule a fresh one after the ramp settles. */
    if(v.pendingSwitch)cancelPendingSwitch(v);
    var newRate=newFreq*(v.transpose||1)/v.sampleFreq;
    var oldRate=v.sourceRate||v.source.playbackRate.value||1;
    /* ── WRAP-DURING-RAMP PROTECTION (position-based) ──
       If the ramp will carry the playhead past loopB, the source plays
       into post-loop buffer content (no native loop). Project position:
         pos_at_ramp_end = sourceOffset + (oldRate+newRate)/2 * durSec
         pos_at_settle   = + newRate * 0.06  (covers 20ms re-anchor delay + margin)
       After commitRampSync above, sourceStartTime === now, so sourceOffset
       is the actual current position. Compare against loopB; if exceeded,
       fire a synchronous immediate switch to re-anchor at pts[a_new]
       with a fresh full-loop ahead.

       Position-based catches fast upward ramps (e.g., 1→8×) that blow
       past loopB inside durSec — the old timeToWrap-at-oldRate check
       missed these because rampAdvance far exceeds oldRate*durSec. */
    if(v.loopPts&&v.loopPts.length>=2&&v.sourceLoopB!==undefined){
      /* Current playhead position: if commitRampSync just ran above,
         v.sourceStartTime === now and the correction is 0. If no prior
         ramp existed, the anchor may be from a past scheduleSegmentSwitch;
         correct for elapsed time at the steady-state rate. */
      var currentPos=v.sourceOffset+oldRate*(now-v.sourceStartTime);
      var rampAdvance=(oldRate+newRate)*0.5*durSec;
      var settlementAdvance=newRate*0.06;
      var projectedPos=currentPos+rampAdvance+settlementAdvance;
      if(projectedPos>=v.sourceLoopB){
        if(v.loopTimer){clearTimeout(v.loopTimer);v.loopTimer=null;}
        doImmediateSwitch(voiceKey);
        v=activeVoices[voiceKey];
        if(!v||!v.alive)return false;
        /* After switch: v.source is NEW, v.sourceStartTime ≈ now+8ms,
           sourceOffset=pts[a_new]. oldRate unchanged (ramp hasn't started). */
        oldRate=v.sourceRate||v.source.playbackRate.value||oldRate;
      }
    }
    /* Start the rate ramp on the current (possibly freshly-switched) source. */
    v.source.playbackRate.cancelScheduledValues(now);
    v.source.playbackRate.setValueAtTime(oldRate,now);
    v.source.playbackRate.linearRampToValueAtTime(newRate,now+durSec);
    v.freq=newFreq;
    /* Record pending ramp for commitRampSync. */
    v.pendingRampStart=now;
    v.pendingRampEnd=now+durSec;
    v.pendingRampR0=oldRate;
    v.pendingRampR1=newRate;
    /* ── RE-ANCHOR AFTER RAMP ──
       Cancel any stale scheduleSegmentSwitch timer (its switchTime was
       computed with oldRate). At ramp-end, call commitRampSync (handles
       post-ramp case: now ≥ re, so anchor = post-ramp position at newRate),
       fold into loop range for clean wrap scheduling, then reschedule. */
    if(v.loopTimer){clearTimeout(v.loopTimer);v.loopTimer=null;}
    var rampStartTime=now;
    var rampEndTime=now+durSec;
    v.reAnchorTimer=setTimeout(function(){
      var v2=activeVoices[voiceKey];
      if(!v2)return;
      v2.reAnchorTimer=null;
      if(!v2.alive)return;
      if(!v2.loopPts||v2.loopPts.length<2)return;
      /* Stale check: if pendingRamp was cleared/replaced (e.g., commitRampSync
         ran already via another sRampFreq), we shouldn't re-commit. */
      if(v2.pendingRampStart!==rampStartTime||v2.pendingRampEnd!==rampEndTime)return;
      var tNow=ctx.currentTime;
      commitRampSync(v2,tNow>rampEndTime?tNow:rampEndTime);
      /* Post-ramp: if source has played past loopB (wrap-during-ramp check
         didn't fire — position was within margin but ramp drift pushed it
         over), the anchor's sourceOffset is past loopB. Fold into loop:
         scheduleSegmentSwitch's switchTime math expects sourceOffset<loopB. */
      var loopA=v2.sourceLoopA,loopB=v2.sourceLoopB;
      if(loopA!==undefined&&loopB!==undefined&&v2.sourceOffset>loopB){
        var loopSpan=loopB-loopA;
        while(v2.sourceOffset>loopB)v2.sourceOffset-=loopSpan;
      }
      scheduleSegmentSwitch(voiceKey);
    },durSec*1000+20);
    return true;
  }
  function sSlideAndFadeOut(voiceKey: string, targetFreq: number, dur: number): number {
    var v=activeVoices[voiceKey];if(!v)return 0.7;
    /* Return baseVol (pre-attenuation) so the caller can pass it to sNoteOnFaded,
       which will reapply attenuation based on the NEW frequency. Falls back to v.vol
       for voices created before baseVol was tracked. */
    var savedVol=(v.baseVol!==undefined)?v.baseVol:v.vol;
    /* Tear down any pre-scheduled switch first; the rate ramp below would
       leave its switchTime/playbackRate stale, and the voice is being
       deleted anyway. */
    if(v.pendingSwitch)cancelPendingSwitch(v);
    if(v.loopTimer){clearTimeout(v.loopTimer);v.loopTimer=null;}
    var now=ctx.currentTime;
    if(v.alive){
      var targetRate=targetFreq*(v.transpose||1)/v.sampleFreq;
      v.source.playbackRate.cancelScheduledValues(now);
      v.source.playbackRate.setValueAtTime(v.source.playbackRate.value,now);
      v.source.playbackRate.linearRampToValueAtTime(targetRate,now+dur);
      v.voiceGain.gain.cancelScheduledValues(now);
      v.voiceGain.gain.setValueAtTime(v.voiceGain.gain.value,now);
      v.voiceGain.gain.linearRampToValueAtTime(0,now+dur);
      try{v.source.stop(now+dur+0.05);}catch(e){}
    }
    delete activeVoices[voiceKey];return savedVol;
  }
  function sNoteOnFaded(voiceKey: string, freq: number, vol: number, dur: number): void {
    if(!ctx||!currentInstrument)return;
    if(activeVoices[voiceKey])sHardStop(voiceKey);
    var nearest=findNearest(freq);if(!nearest)return;
    var instr=INSTRUMENTS[currentInstrument];
    var rate=freq*(instr.transpose||1)/nearest.freq;
    /* vol param is treated as baseVol (without range attenuation);
       apply attenuation fresh based on current freq */
    var baseVol=vol;
    vol=baseVol*rangeAttenuation(freq);
    var pts=nearest.lp&&nearest.lp.loopPts;
    var source=ctx.createBufferSource();source.buffer=nearest.buffer;
    source.playbackRate.value=rate;
    /* start from loop region (no attack re-trigger) */
    var startOffset;
    if(instr.loop&&pts&&pts.length>=2){
      /* No source.loop=true — scheduleSegmentSwitch handles all looping. */
      source.loopStart=pts[0];source.loopEnd=pts[pts.length-1];
      startOffset=pts[0]; /* start at loop point, not beginning */
    } else {
      startOffset=(nearest.lp&&nearest.lp.trimStart)?nearest.lp.trimStart:0;
    }
    var pressureGain=ctx.createGain();pressureGain.gain.value=1.0;pressureGain.connect(master);
    var damperGain=ctx.createGain();damperGain.gain.value=1.0;damperGain.connect(pressureGain);
    var voiceGain=ctx.createGain();voiceGain.gain.value=1.0;voiceGain.connect(damperGain);
    var segGain=ctx.createGain();
    /* Pre-schedule 50ms ahead so source.start isn't clamped under any
       plausible JS stall — see the longer comment in sNoteOn for the
       full rationale. */
    /* Snap to the next integer audio sample so every source we ever start
       has a sample-aligned `when`. Combined with sample-aligned offsets
       (trimStart / pts[a] are snapped at sample-load time), this means at
       rate=1 the audio engine reads the buffer at integer sample positions
       throughout — no interpolation, and identical sub-sample alignment
       across the first source and every subsequent source. */
    var startT=Math.ceil((ctx.currentTime+0.050)*ctx.sampleRate)/ctx.sampleRate;
    segGain.gain.setValueAtTime(0,startT);segGain.gain.linearRampToValueAtTime(vol,startT+dur);
    source.connect(segGain);segGain.connect(voiceGain);
    source.start(startT,startOffset);
    /* Graph: accept new validStartsByEnd or convert legacy endsByStart */
    var vsbeFaded=nearest.lp&&nearest.lp.validStartsByEnd;
    if(!vsbeFaded&&nearest.lp&&nearest.lp.endsByStart&&pts){
      var legacyEBS=nearest.lp.endsByStart;
      vsbeFaded=new Array(pts.length);
      for(var li=0;li<pts.length;li++)vsbeFaded[li]=[];
      for(var la=0;la<legacyEBS.length;la++){
        var bs=legacyEBS[la]||[];
        for(var lk=0;lk<bs.length;lk++){
          var lb=bs[lk];
          if(lb>la&&lb<pts.length)vsbeFaded[lb].push(la);
        }
      }
    }
    var voice={source:source,segGain:segGain,voiceGain:voiceGain,damperGain:damperGain,pressureGain:pressureGain,freq:freq,sampleFreq:nearest.freq,transpose:(instr.transpose||1),sampleName:nearest.name,vol:vol,baseVol:baseVol,alive:true,
      loopPts:pts,validStartsByEnd:vsbeFaded||null,loopTimer:null,buffer:nearest.buffer,instr:instr,
      slopeCV:(nearest.lp&&typeof nearest.lp.slopeCV==='number')?nearest.lp.slopeCV:0.5,
      /* Source anchor — see comment in sNoteOn */
      sourceStartTime:startT,sourceOffset:startOffset,
      sourceLoopA:(pts&&pts.length>=2)?pts[0]:0,
      sourceLoopB:(pts&&pts.length>=2)?pts[pts.length-1]:0,
      sourceLoopAIdx:0,
      sourceLoopBIdx:(pts&&pts.length>=2)?pts.length-1:0,
      sourceRate:rate};
    source.onended=function(){voice.alive=false;};
    activeVoices[voiceKey]=voice;
    if(instr.loop&&pts&&pts.length>=2){
      scheduleSegmentSwitch(voiceKey);
    }
  }
  function sHardStop(voiceKey: string): void {
    var v=activeVoices[voiceKey];if(!v)return;
    if(v.loopTimer){clearTimeout(v.loopTimer);v.loopTimer=null;}
    if(v.reAnchorTimer){clearTimeout(v.reAnchorTimer);v.reAnchorTimer=null;}
    if(v.pendingSwitch)cancelPendingSwitch(v);
    if(v.alive){v.voiceGain.gain.cancelScheduledValues(ctx.currentTime);v.voiceGain.gain.setValueAtTime(0,ctx.currentTime);try{v.source.stop(ctx.currentTime);}catch(e){}}
    delete activeVoices[voiceKey];
  }
  function sHardStopAll(): void {for(var k in activeVoices)sHardStop(k);}
  function sStopAll(): void {for(var k in activeVoices)sNoteOff(k);}
  function sSetAftertouch(voiceKey: string, targetGain: number, rampSec: number): void {
    var v=activeVoices[voiceKey];if(!v||!v.alive||!v.pressureGain)return;
    var now=ctx.currentTime;
    v.pressureGain.gain.cancelScheduledValues(now);
    v.pressureGain.gain.setValueAtTime(v.pressureGain.gain.value,now);
    v.pressureGain.gain.linearRampToValueAtTime(targetGain,now+rampSec);
  }
  /* Continuous-damper modulation. tau=0 → instant set (sostenuto pin), else
     setTargetAtTime exponential smoothing. Engine guarantees sample voices
     have a damperGain via sNoteOn/sNoteOnFaded. */
  function sSetVoiceDamperDepth(voiceKey: string, depth: number, tau: number): void {
    var v=activeVoices[voiceKey];if(!v||!v.alive||!v.damperGain)return;
    var now=ctx.currentTime;
    v.damperGain.gain.cancelScheduledValues(now);
    if(tau<=0){v.damperGain.gain.setValueAtTime(depth,now);}
    else{v.damperGain.gain.setTargetAtTime(depth,now,tau);}
  }
  return{INSTRUMENTS:INSTRUMENTS,init:init,loadInstrument:loadInstrument,
    noteOn:sNoteOn,noteOff:sNoteOff,rampFreq:sRampFreq,
    slideAndFadeOut:sSlideAndFadeOut,noteOnFaded:sNoteOnFaded,
    hardStop:sHardStop,hardStopAll:sHardStopAll,stopAll:sStopAll,
    setAftertouch:sSetAftertouch,
    setVoiceDamperDepth:sSetVoiceDamperDepth,
    getActiveVoices:function(){return activeVoices;},
    isLoaded:function(){return !!(currentInstrument&&buffers[currentInstrument]);},
    setInstrument:function(k: string){if(buffers[k])currentInstrument=k;},
    isInstrumentLoaded:function(k: string){return !!buffers[k];},
    unloadInstrument:function(k: string){delete buffers[k];},
    /* Diagnostics: lets loopOverlay attach an AnalyserNode to the samples-only
       master so envelope visualization captures sample voices without
       oscillator content. Connects in parallel to the existing destination. */
    tapMaster:function(node: AudioNode){if(master)master.connect(node);}};
})();
